/* Momentum Factory — learning-funded machines, worker automation and a visible supply chain. */
(function (global) {
 'use strict';
 const ORDER = ['supply','press','assembly','packing','shipping'];
 const TYPES = {
  supply:{name:'מחסן העצים',detail:'העובד אוסף עצים מהיער ומביא אותם למפעל. תנו לו עובד, והוא ימשיך לאסוף לבד!',input:null,output:'raw'},
  press:{name:'מכונת החלקים',detail:'כאן העצים הופכים לחלקים קטנים. מהם נבנה את הרובוטים שלנו!',input:'raw',output:'parts'},
  assembly:{name:'בונה הרובוטים',detail:'החלקים נכנסים, ורובוט חדש יוצא! שדרוג מוסיף זרועות ועוזר להכין עוד רובוטים.',input:'parts',output:'products'},
  packing:{name:'אורזת ההפתעות',detail:'כל רובוט מקבל ארגז משלו, כדי להגיע בשלום לחבר החדש שלו.',input:'products',output:'boxes'},
  shipping:{name:'עמדת המשלוחים',detail:'המנוף שולח את הארגזים לחנות. כשהלקוח מקבל אותם, אתם מרוויחים מטבעות!',input:'boxes',output:null}
 };
 const BUILD_COSTS={supply:3,press:10,assembly:10,packing:10,shipping:10}, OUTLET_COSTS={raw:3,parts:18};
 const PRICES=[10,15,20], CASH=[0,10,20], RESOURCES={raw:'עצים',parts:'חלקים',products:'רובוטים',boxes:'ארגזים'};
 const CONTRACTS=[{name:'ההזמנה הראשונה',product:'צעצועים ראשונים',grade:1,target:12,value:5},{name:'מכינים הפתעות',product:'ערכות המצאה',grade:2,target:12,value:10},{name:'חברים רובוטיים',product:'רובוטים מדויקים',grade:3,target:18,value:20}];
 const copy=v=>JSON.parse(JSON.stringify(v));
 const building=(s,type)=>s.buildings.find(b=>b&&b.type===type);
 const siteOf=(s,type)=>s.buildings.findIndex(b=>b&&b.type===type);
 const activeLevel=(s,type)=>{const b=building(s,type);return b&&!b.pending?b.level:0;};
 const assigned=s=>s.buildings.filter(b=>b&&b.worker).length;
 const total=(s,key)=>s.stock[key].reduce((a,b)=>a+b,0);
 function productionGrade(s){return Math.max(1,Math.min(s.order+1,3,...ORDER.map(t=>activeLevel(s,t))));}
 function fresh(){return {market:null,version:1,points:0,earned:0,spent:0,money:0,employees:1,buildings:[null,null,null,null,null,null,null],stock:{raw:[0,0,0],parts:[0,0,0],products:[0,0,0],boxes:[0,0,0]},jobs:[],time:0,order:0,delivered:0,sold:0,started:false,outcome:null,event:'בנו תחנות, שייכו עובדים והפעילו את קו הייצור.'};}
 // A single FIFO queue, visible shop stock and a dedicated collection/delivery worker.
 function prepareMarket(s){
  if(!s.market)s.market={outlets:{raw:false,parts:false},paused:{},revenue:0,visits:0,receipts:[]};
  const m=s.market;if(m.version!==2){m.version=2;m.customers=[];m.counter=[];m.porter=null;m.arrival=2000;m.nextId=0;}
  if(!m.paused)m.paused={};return m;
 }
 function openOutlet(s,kind){const m=prepareMarket(s),cost=OUTLET_COSTS[kind];if(!['raw','parts'].includes(kind)||m.outlets[kind]||s.points<cost||s.outcome)return false;s.points-=cost;s.spent+=cost;m.outlets[kind]=true;s.event='נפתח אפיק הכנסה נוסף: '+RESOURCES[kind];return true;}
 function availableStock(s,kind,grade,ignoreSpecial=false){
  const reserved=s.jobs.filter(j=>j.input===kind&&j.grade===grade&&!j.picked).reduce((n,j)=>n+j.amount,0),p=prepareMarket(s).porter,extra=s.play&&s.play.special;
  return Math.max(0,s.stock[kind][grade-1]-reserved-(p&&p.kind===kind&&p.grade===grade&&!p.picked?p.amount:0)-(!ignoreSpecial&&extra&&extra.kind===kind&&extra.grade===grade&&!extra.picked?extra.amount:0));
 }
 function saleStock(s,kind,grade){const downstream=building(s,{raw:'press',parts:'assembly',products:'packing'}[kind]);return Math.max(0,availableStock(s,kind,grade)-(downstream?downstream.level:0));}
 function automaticOutlet(s,kind){const m=prepareMarket(s);return !m.paused[kind]&&(kind==='products'?activeLevel(s,'assembly')>0:!!m.outlets[kind]);}
 function receipt(s,amount){s.money+=amount;const m=prepareMarket(s);m.revenue=(m.revenue||0)+amount;m.receipts.push({time:s.time,amount});}
 function moveCustomer(c,target){c.from=c.position;c.target=target;c.elapsed=0;c.duration=Math.max(700,Math.abs(target-c.position)*550);c.phase='moving';}
 function marketStep(s,dt){specialStep(s,dt);const m=prepareMarket(s);m.receipts=m.receipts.filter(r=>s.time-r.time<60000);
  m.arrival=Math.max(0,m.arrival-dt);
  if(!m.arrival&&m.customers.filter(c=>c.phase!=='leaving').length<5){const rank=m.customers.filter(c=>c.phase!=='leaving').length,c={slot:m.nextId++,position:6,from:6,target:rank,phase:'moving',elapsed:0,duration:(6-rank)*550,paid:0,kind:'boxes'};m.customers.push(c);m.arrival=4000;}
  for(const c of m.customers){if(c.phase==='moving'){c.elapsed=Math.min(c.duration,c.elapsed+dt);c.position=c.from+(c.target-c.from)*c.elapsed/c.duration;if(c.elapsed===c.duration){c.phase='waiting';c.elapsed=0;}}else if(c.phase==='leaving')c.elapsed=Math.min(c.duration,c.elapsed+dt);}
  m.customers=m.customers.filter(c=>c.phase!=='leaving'||c.elapsed<c.duration);
  const queue=m.customers.filter(c=>c.phase!=='leaving');queue.forEach((c,i)=>{if(c.phase==='waiting'&&c.position!==i)moveCustomer(c,i);});
  const head=queue[0];
  if(head&&head.phase==='waiting'&&head.position===0&&m.counter.length){head.elapsed+=dt;if(head.elapsed>=1200){const lot=m.counter.shift(),cash=lot.amount*(lot.kind==='boxes'?CONTRACTS[lot.grade-1].value:(lot.kind==='raw'?2:lot.kind==='parts'?4:6)*lot.grade);receipt(s,cash);head.kind=lot.kind;head.phase='leaving';head.elapsed=0;head.duration=2200;head.paid=cash;m.visits++;s.event='הלקוח קיבל את הסחורה ושילם '+cash+' מטבעות';if(lot.kind==='boxes'){s.sold+=lot.amount;if(lot.grade===s.order+1)s.delivered+=lot.amount;if(!s.endless&&s.delivered>=CONTRACTS[Math.min(2,s.order)].target){s.order++;s.delivered=0;s.outcome=s.order===3?'victory':'milestone';s.event=s.order===3?'המפעל משגשג — כל יעדי ההתרחבות הושלמו!':'היעד הושלם! אפשר להרחיב את קו הייצור.';}}}}
  if(s.outcome)return;
  let p=m.porter;
  if(!p&&m.counter.length<6){for(const kind of ['products','parts','raw']){if(!automaticOutlet(s,kind))continue;const source=siteOf(s,{raw:'supply',parts:'press',products:'assembly'}[kind]);if(source<1)continue;const grade=s.stock[kind].findIndex((n,i)=>saleStock(s,kind,i+1)>0)+1;if(!grade)continue;p={kind,grade,amount:Math.min(2,saleStock(s,kind,grade)),source,phase:'out',elapsed:0,duration:1800,picked:false};m.porter=p;break;}}
  if(p){p.elapsed=Math.min(p.duration,p.elapsed+dt);if(p.elapsed===p.duration){if(p.phase==='out'){s.stock[p.kind][p.grade-1]-=p.amount;p.picked=true;p.phase='carry';p.elapsed=0;p.duration=1800;}else{m.counter.push({kind:p.kind,grade:p.grade,amount:p.amount});m.porter=null;}}}
 }
 function keepTrading(s){if(s.outcome!=='victory')return false;s.outcome=null;s.endless=true;s.started=true;s.event='המפעל ממשיך לפעול — לקוחות חדשים מגיעים, הייצור והמכירות נמשכים.';return true;}
 function reward(s){s.points++;s.earned++;const p=preparePlay(s);p.energy=Math.min(3,p.energy+1);}
 function nextBuild(s){return ORDER.find(t=>!building(s,t));}
 function buy(s,site,type){
  if(s.outcome||!Number.isInteger(site)||site<1||site>=s.buildings.length||s.buildings[site]||!TYPES[type]||type!==nextBuild(s)||building(s,type)||s.points<BUILD_COSTS[type])return false;
  s.points-=BUILD_COSTS[type];s.spent+=BUILD_COSTS[type];s.buildings.splice(site,1,{type,level:1,worker:false,conveyor:false,pending:3000,manual:false});s.event=TYPES[type].name+' בהתקנה';return true;
 }
 function cancelJob(s,site){const job=s.jobs.find(j=>j.site===site);if(job&&job.picked&&job.input)s.stock[job.input][job.grade-1]+=job.amount;s.jobs=s.jobs.filter(j=>j.site!==site);}
 function upgrade(s,site){const b=s.buildings[site];if(s.outcome||!b||b.pending||b.level===3||s.points<PRICES[b.level]||s.money<CASH[b.level])return false;
  cancelJob(s,site);s.points-=PRICES[b.level];s.spent+=PRICES[b.level];s.money-=CASH[b.level];b.level++;b.pending=3000;b.manual=false;s.event=TYPES[b.type].name+' משתדרג';return true;
 }
 function hire(s){if(s.outcome||s.employees===5||s.points<5)return false;s.points-=5;s.spent+=5;s.employees++;s.event='עובד חדש הצטרף. בחרו תחנה ושייכו אותו.';return true;}
 function assign(s,site){const b=s.buildings[site];if(s.outcome||!b||b.pending||(!b.worker&&assigned(s)>=s.employees))return false;cancelJob(s,site);b.worker=!b.worker;s.event=b.worker?'העובד משויך ל'+TYPES[b.type].name:'העובד פנוי לשיוך אחר';return true;}
 function relocate(s,from,to){if(s.outcome||!s.buildings[from]||from===to||to<1||to>=s.buildings.length||s.buildings[to])return false;for(const j of s.jobs.slice())if(j.site===from||j.source===from)cancelJob(s,j.site);const p=prepareMarket(s).porter;if(p&&p.source===from){if(p.picked)s.stock[p.kind][p.grade-1]+=p.amount;s.market.porter=null;}const special=s.play&&s.play.special;if(special&&special.source===from)cancelSpecial(s);const b=s.buildings[from];s.buildings.splice(from,1,null);s.buildings.splice(to,1,b);s.event='התחנה הועברה ללא עלות';return true;}
 function manual(s,site){const b=s.buildings[site];if(s.outcome||!b||b.pending||b.manual||s.jobs.some(j=>j.site===site))return false;b.manual=true;s.started=true;return true;}
 function hasConveyor(b){return !!b&&b.type!=='supply'&&(b.conveyor===true||b.level>=2);}
 function buyConveyor(s,site){const b=s.buildings[site];if(s.outcome||!b||b.pending||b.type==='supply'||hasConveyor(b)||s.money<10)return false;cancelJob(s,site);s.money-=10;s.buildings.splice(site,1,{...b,conveyor:true});s.event='המסוע מחובר! החומרים מגיעים מהר יותר והעובד נשאר ליד המכונה.';return true;}
 function walks(j){return j.phase==='delivery'||j.phase!=='work'&&!j.conveyor;}
 function duration(b,phase){if(hasConveyor(b)&&['out','fetch'].includes(phase))return phase==='out'?300:900;const base=phase==='work'?[6000,4000,2400][b.level-1]:phase==='delivery'?3000:2000;return Math.round(base*(phase==='work'?(b.worker?.65:1):.65)*(phase==='work'?1:1/(1+(b.level-1)*.3)));}
 function sourceSite(s,type){const i=ORDER.indexOf(type);return i>0?Math.max(0,siteOf(s,ORDER[i-1])):0;}
 function complete(s,j){
  if(j.type==='shipping'){prepareMarket(s).counter.push({kind:'boxes',grade:j.grade,amount:j.amount});s.event='המשלוח הונח בדוכן וממתין ללקוח הראשון';}
  else{s.stock[TYPES[j.type].output][j.grade-1]+=j.amount;s.event=TYPES[j.type].name+': הושלמו '+j.amount+' '+RESOURCES[TYPES[j.type].output];}
  s.jobs=s.jobs.filter(v=>v!==j);
 }
 function stepWorld(s,dt){
  if(!s.started||s.outcome||dt<=0)return false;s.time+=dt;marketStep(s,dt);if(s.outcome)return true;let changed=false;
  for(const b of s.buildings)if(b&&b.pending){b.pending=Math.max(0,b.pending-dt);if(!b.pending){s.event=TYPES[b.type].name+' מוכן';changed=true;}}
  const grade=productionGrade(s);
  for(let site=1;site<s.buildings.length;site++){
   const b=s.buildings[site];if(!b||b.pending)continue;let j=s.jobs.find(v=>v.site===site);
   if(!j){
    if(!b.worker&&b.level<2&&!b.manual)continue;if(b.type==='shipping'&&prepareMarket(s).counter.length>=6)continue;
    const type=TYPES[b.type],available=type.input?availableStock(s,type.input,grade):40,room=type.output?40-s.stock[type.output][grade-1]:40,amount=Math.min(b.level,available,room);
    if(amount<=0)continue;
    j={site,type:b.type,input:type.input,grade,amount,source:sourceSite(s,b.type),phase:'out',elapsed:0,duration:duration(b,'out'),worker:b.worker,conveyor:hasConveyor(b),picked:false};
    if(j.picked&&j.input)s.stock[j.input][grade-1]-=amount;
    s.jobs.push(j);b.manual=false;changed=true;
   }
   j.elapsed=Math.min(j.duration,j.elapsed+dt);if(j.elapsed<j.duration)continue;
   if(j.phase==='out'){
    if(j.input)s.stock[j.input][j.grade-1]-=j.amount;j.picked=true;j.phase='fetch';j.elapsed=0;j.duration=duration(b,'fetch');
   }else if(j.phase==='fetch'){j.phase='work';j.elapsed=0;j.duration=duration(b,'work');}
   else if(j.phase==='work'&&b.type==='shipping'){j.phase='delivery';j.elapsed=0;j.duration=duration(b,'delivery');}
   else complete(s,j);
   changed=true;if(s.outcome)break;
  }
  return changed;
 }
 // All playful feedback uses the same paused, persisted simulation clock.
 function preparePlay(s){
  if(!s.play)s.play={energy:0,boost:0,boosts:0,skin:'gold',seen:[],sound:true};
  if(s.play.deliveries===undefined)s.play.deliveries=0;if(s.play.special===undefined)s.play.special=null;
  return s.play;
 }
 const SPECIAL_ORDERS={raw:{name:'עצים לסדנת ההמצאות',amount:3,cash:12,art:'raw',visitor:'mint'},parts:{name:'גלגלים לחבר חדש',amount:2,cash:16,art:'part',visitor:'berry'}};
 function specialGrade(s,kind){const request=SPECIAL_ORDERS[kind];return request?s.stock[kind].findIndex((n,i)=>availableStock(s,kind,i+1)>=request.amount)+1:0;}
 function canSpecial(s,kind){return !!SPECIAL_ORDERS[kind]&&!s.outcome&&!preparePlay(s).special&&prepareMarket(s).visits>0&&siteOf(s,kind==='raw'?'supply':'press')>0;}
 function startSpecial(s,kind){
  if(!canSpecial(s,kind))return false;const request=SPECIAL_ORDERS[kind];
  preparePlay(s).special={kind,amount:request.amount,cash:request.cash,grade:specialGrade(s,kind)||productionGrade(s),source:siteOf(s,kind==='raw'?'supply':'press'),picked:false,phase:specialGrade(s,kind)?'out':'gather',elapsed:0,duration:1800};
  s.event='העובד שומר חומרים ואוסף את ההזמנה המיוחדת';return true;
 }
 function cancelSpecial(s){const p=s.play&&s.play.special;if(!p)return false;if(p.picked)s.stock[p.kind][p.grade-1]+=p.amount;s.play.special=null;s.event='ההזמנה נשמרת לפעם אחרת. החומרים נשארים שלכם.';return true;}
 function specialStep(s,dt){
  const p=s.play&&s.play.special;if(!p)return;if(p.phase==='gather'){const ready=s.stock[p.kind].findIndex((n,i)=>availableStock(s,p.kind,i+1,true)>=p.amount)+1;p.grade=ready||productionGrade(s);if(!ready)return;p.phase='out';p.elapsed=0;return;}p.elapsed=Math.min(p.duration,p.elapsed+dt);if(p.elapsed<p.duration)return;
  if(p.phase==='out'){s.stock[p.kind][p.grade-1]-=p.amount;p.picked=true;p.phase='carry';p.elapsed=0;p.duration=1800;}
  else if(p.phase==='carry'){p.phase='handoff';p.elapsed=0;p.duration=1000;}
  else{s.play.special=null;s.play.deliveries++;receipt(s,p.cash);s.event='ההפתעה הגיעה לחבר! הרווחתם '+p.cash+' מטבעות';}
 }
 function boost(s){const p=preparePlay(s);if(!s.started||s.outcome||p.energy<3||p.boost>0)return false;p.energy-=3;p.boost=8000;p.boosts++;s.event='טורבו! כל המפעל עובד במהירות כפולה';return true;}
 function step(s,dt){
  if(!s.started||s.outcome||dt<=0)return false;
  const p=preparePlay(s),extra=Math.min(dt,p.boost);p.boost-=extra;
  let changed=false;for(let left=dt+extra;left>0&&!s.outcome;left-=100)changed=stepWorld(s,Math.min(100,left))||changed;
  return changed;
 }
 const BADGES=[
  {id:'builder',name:'בונים חלומות',detail:'בניתם את המכונה הראשונה',art:'supply-1',goal:'בנו מכונה ראשונה',test:s=>s.buildings.some(Boolean)},
  {id:'seller',name:'הלקוח הראשון',detail:'המוצר הראשון הגיע ללקוח',art:'box',goal:'מכרו ללקוח הראשון',test:s=>prepareMarket(s).visits>0},
  {id:'team',name:'צוות מנצח',detail:'שלושה עובדים במפעל שלכם',art:'crew-gold',goal:'גייסו שלושה עובדים',test:s=>s.employees>=3},
  {id:'line',name:'קסם המכונות',detail:'כל חמש המכונות עובדות יחד',art:'assembly-2',goal:'בנו את כל חמש המכונות',test:s=>s.buildings.filter(Boolean).length===5},
  {id:'mint',name:'הצוות הירוק',detail:'בגדי הצוות הירוקים נפתחו!',art:'crew-mint',goal:'השלימו את ההזמנה הראשונה',skin:'mint',test:s=>s.order>=1},
  {id:'berry',name:'הצוות הסגול',detail:'בגדי הצוות הסגולים נפתחו!',art:'crew-berry',goal:'השלימו את ההזמנה השנייה',skin:'berry',test:s=>s.order>=2},
  {id:'turbo',name:'על טורבו',detail:'הפעלתם את המפעל במהירות כפולה',art:'press-3',goal:'הפעילו טורבו פעם אחת',test:s=>preparePlay(s).boosts>0},
  {id:'helper',name:'חבר של השכונה',detail:'מסרתם הפתעה לחבר במו ידיכם',art:'crew-mint',goal:'שלחו הזמנה מיוחדת מהחנות',test:s=>preparePlay(s).deliveries>0},
  {id:'master',name:'מפעל החלומות',detail:'השלמתם את כל שלוש ההזמנות!',art:'shipping-3',goal:'השלימו שלוש הזמנות',test:s=>s.order>=3}
 ];
 function setSkin(s,skin){if(!['gold','mint','berry'].includes(skin)||skin!=='gold'&&!BADGES.find(b=>b.skin===skin).test(s))return false;preparePlay(s).skin=skin;return true;}
 function nextOrder(s){if(s.outcome!=='milestone')return false;s.outcome=null;s.event='שדרגו את התחנה האיטית בקו. אפשר להמשיך למכור מוצרים קיימים למימון השדרוגים.';return true;}
 // Guidance is derived from the real save, so returning players never repeat a tutorial.
 function guidance(s){
  const m=prepareMarket(s),supply=building(s,'supply');
  const task=(title,text,action,label,cost=0,site=-1,type=null)=>({title,text,action,label,cost,site,type});
  const buildTask=type=>task('בונים '+TYPES[type].name,type==='supply'?'עונים על 3 שאלות ובונים מחסן. העובד יתחיל לאסוף עצים לבד!':'נוסיף מכונה חדשה ונגלה מה היא יכולה להכין!', 'build','בונים עכשיו · '+BUILD_COSTS[type]+' כוכבים',BUILD_COSTS[type],s.buildings.findIndex((b,i)=>i>0&&!b),type);
  if(!supply)return buildTask('supply');
  const pending=s.buildings.findIndex(b=>b&&b.pending);
  if(pending>0)return task('המכונה החדשה בדרך!','הפעילו את המפעל. בעוד כמה שניות המכונה תהיה מוכנה.','wait','ממשיכים לעבוד',0,pending);
  const idle=s.buildings.findIndex(b=>b&&b.level===1&&!b.worker);
  if(idle>0){
   if(assigned(s)<s.employees)return task('נותנים לעובד מכונה','העובד מביא חומרים ומפעיל את המכונה. בהמשך נקנה מסוע! השיוך חינם!','assign','העובד מתחיל כאן',0,idle);
   return task('מצרפים חבר לצוות','צריך עוד עובד כדי שהמכונה החדשה תעבוד לבד.','hire','מגייסים עובד · 5 כוכבים',5,idle);
  }
  if(!m.visits&&!m.outlets.raw&&!s.sold)return task('פותחים חנות קטנה','נמכור עצים ללקוחות ונרוויח מטבעות לקניית שדרוגים.','outlet','פותחים חנות · 3 כוכבים',3);
  if(!m.visits&&!s.sold){
   if(m.paused.raw)return task('פותחים שוב את החנות','הלקוחות מחכים לעצים שלנו.','resume','מחדשים מכירת עצים');
   return task('מחכים ללקוח הראשון','עקבו אחרי השליח: הוא מביא סחורה למוכר בחנות, והלקוח משלם!','wait','המפעל עובד בשבילנו');
  }
  const next=nextBuild(s);if(next)return buildTask(next);
  const level=Math.min(3,s.order+1),site=s.buildings.findIndex(b=>b&&b.level<level);
  if(site>0){const b=s.buildings[site];if(s.money<CASH[b.level])return task('מרוויחים לשדרוג הבא','חסרים עוד '+(CASH[b.level]-s.money)+' מטבעות. המפעל ממשיך למכור בינתיים.','wait','מחכים למכירות');return task('משדרגים '+TYPES[b.type].name,'כל המכונות צריכות להגיע לדרגה '+level+' כדי להכין את ההזמנה החדשה.','upgrade','משדרגים · '+PRICES[b.level]+' כוכבים + '+CASH[b.level]+' מטבעות',PRICES[b.level],site);}
  return task(s.endless?'איזה מפעל בנינו!':'מכינים את ההזמנה','המכונות עובדות יחד. הארגזים מגיעים לחנות והלקוחות משלמים.','wait','ממשיכים לייצר');
 }
 // Read the physical line, including stock already reserved for another worker.
 function stationStatus(s,site){const b=s.buildings[site];if(!b)return {key:'empty',label:'כאן בונים'};if(b.pending)return {key:'install',label:'המכונה נבנית…'};
  const j=s.jobs.find(j=>j.site===site),t=TYPES[b.type];if(j)return {key:j.phase,label:j.phase==='work'?(b.type==='supply'?'אוספים עצים':b.type==='press'?'מכינים חלקים':b.type==='assembly'?'בונים רובוט':b.type==='packing'?'אורזים רובוט':'מכינים משלוח'):j.phase==='delivery'?'שולחים לחנות':j.phase==='out'?(j.conveyor?'טוענים את המסוע':'העובד בדרך לחומרים'):(j.conveyor?'חומרים מגיעים על המסוע':'העובד מביא חומרים')};
  if(!b.worker&&b.level<2&&!b.manual)return {key:'worker',label:'מחכה לעובד'};
  const grade=productionGrade(s);if(t.output&&s.stock[t.output][grade-1]>=40)return {key:'full',label:'המלאי מלא — מחכים לפינוי'};
  if(b.type==='shipping'&&prepareMarket(s).counter.length>=6)return {key:'full',label:'החנות מלאה — מחכים לקונים'};
  if(t.input&&!availableStock(s,t.input,grade))return {key:'input',label:'מחכה ל'+RESOURCES[t.input],source:siteOf(s,ORDER[ORDER.indexOf(b.type)-1])};
  return {key:'ready',label:'מוכן לסיבוב הבא'};
 }
 function speedPlan(s){const sites=s.buildings.map((b,i)=>({b,i})).filter(v=>v.b&&!v.b.pending);if(!sites.length)return null;
  const idle=sites.find(v=>v.b.level===1&&!v.b.worker);if(idle)return {action:assigned(s)<s.employees?'assign':'hire',site:idle.i,cost:assigned(s)<s.employees?0:5,cash:0,title:'עובד קבוע ל'+TYPES[idle.b.type].name,text:'העובד יביא חומרים ויפעיל את המכונה שוב ושוב. בהמשך נקנה מסוע ונאיץ את ההעברה!',label:assigned(s)<s.employees?'מצרפים עובד פנוי':'מצרפים עובד · 5 כוכבים'};
  const belt=sites.find(v=>v.b.type!=='supply'&&!hasConveyor(v.b));if(belt)return {action:'conveyor',site:belt.i,cost:0,cash:10,title:'מסוע ל'+TYPES[belt.b.type].name,text:'במקום ללכת להביא חומרים, העובד נשאר ליד המכונה. המסוע מביא אותם בפחות מחצי מהזמן!',label:'קונים מסוע · 10 מטבעות'};
  const next=sites.filter(v=>v.b.level<3).sort((a,b)=>a.b.level-b.b.level||a.i-b.i)[0];if(!next)return null;
  return {action:'upgrade',site:next.i,cost:PRICES[next.b.level],cash:CASH[next.b.level],title:'מאיצים את '+TYPES[next.b.type].name,text:'בכל סיבוב נכין '+(next.b.level+1)+' במקום '+next.b.level+'. המכונה גם תעבוד מהר יותר!',label:'משדרגים את המכונה',before:next.b.level,after:next.b.level+1};
 }
 function applySpeed(s){const p=speedPlan(s);if(!p||s.outcome||s.points<p.cost||s.money<p.cash)return false;if(p.action==='conveyor')return buyConveyor(s,p.site);if(p.action==='upgrade')return upgrade(s,p.site);if(p.action==='hire'&&!hire(s))return false;return assign(s,p.site);}
 function guidedBuild(s,site,type){if(!buy(s,site,type))return false;const b=s.buildings[site];if(assigned(s)<s.employees)b.worker=true;s.started=true;return true;}
 function themeKit(theme){const c=theme.colors,hex=c.primary.replace('#',''),rgb=[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16)),light=(rgb[0]*299+rgb[1]*587+rgb[2]*114)/1000>145;return {'--mf-paper':c.background,'--mf-ink':c.text,'--mf-primary':c.primary,'--mf-accent':c.accent,'--mf-tint':c.tertiary,'--mf-button-ink':light?'#172d37':'#ffffff'};}
 function createMomentumFactoryComponent(Base){return Vue.component('momentum-factory',Vue.extend({extends:Base,
  data(){const factory=fresh();prepareMarket(factory);preparePlay(factory);return {factory,phase:'opening',resumePhase:'planning',newWords:[],newWordIndex:0,question:null,options:[],wrongIndex:-1,feedback:'',selectedSite:-1,movingSite:-1,stopped:false,hidden:false,reduced:false,types:TYPES,resources:RESOURCES,contracts:CONTRACTS,art:global.MOMENTUM_ART,revision:0,buildCosts:BUILD_COSTS,outletCosts:OUTLET_COSTS,specialOrders:SPECIAL_ORDERS,practiceTarget:null,notice:null,overview:false};},
  computed:{speedLabel(){return !this.speed?'':this.factory.points<this.speed.cost?'לומדים עוד '+(this.speed.cost-this.factory.points)+' תשובות לשיפור':this.speed.label;},speed(){return speedPlan(this.factory);},practiceGoal(){return this.practiceTarget||this.guide;},practiceRemaining(){return Math.max(0,this.practiceGoal.cost-this.factory.points);},workingCount(){return this.factory.jobs.length;},lineStations(){return this.factory.buildings.map((b,site)=>b?{b,site,status:stationStatus(this.factory,site)}:null).filter(Boolean);},play(){return preparePlay(this.factory);},badges(){return BADGES.map(b=>({...b,unlocked:b.test(this.factory)}));},newBadges(){return this.badges.filter(b=>b.unlocked&&!this.play.seen.includes(b.id)).length;},guide(){return guidance(this.factory);},guideRemaining(){return Math.max(0,this.guide.cost-this.factory.points);},guideLabel(){return this.guideRemaining?'לומדים · עוד '+this.guideRemaining+' כוכבים':this.guide.action==='wait'&&this.phase!=='running'?'מפעילים את המפעל':this.guide.label;},nextMachine(){return nextBuild(this.factory);},nextSite(){return this.factory.buildings.findIndex((b,i)=>i>0&&!b);},visibleTypes(){return this.nextMachine?{[this.nextMachine]:TYPES[this.nextMachine]}:{};},supplyStation(){return building(this.factory,'supply');},spareEmployee(){return assigned(this.factory)<this.factory.employees;},prosperity(){const total=this.factory.buildings.reduce((n,b)=>n+(b?b.level:0),0);return total>=15?'מפעל משגשג':total>=10?'תעשייה אוטומטית':total>=5?'עסק בצמיחה':'בית מלאכה קטן';},market(){return prepareMarket(this.factory);},income(){return this.market.receipts.reduce((n,r)=>n+r.amount,0);},kit(){return themeKit(this.theme);},learning(){return this.newWords.length>0||['ready','retry','resolved'].includes(this.phase);},selected(){return this.factory.buildings[this.selectedSite];},canManage(){return !this.learning&&!this.factory.outcome&&this.phase!=='opening';},workers(){return assigned(this.factory)+' / '+this.factory.employees;},contract(){return CONTRACTS[Math.min(2,this.factory.order)];},grade(){return productionGrade(this.factory);},connections(){const links=[];for(let i=1;i<ORDER.length;i++){const a=siteOf(this.factory,ORDER[i-1]),b=siteOf(this.factory,ORDER[i]);if(a>0&&b>0&&hasConveyor(this.factory.buildings[b]))links.push({a,b});}return links;}},
  template:`<main class="mf-game" :style="kit" :class="{'mf-overview':overview,'mf-opening':phase==='opening','mf-reduced':reduced,'mf-paused':phase!=='running'||hidden||newWords.length>0,'mf-boosting':play.boost>0,'mf-modal-open':learning||phase==='opening'||!!factory.outcome,'mf-skin-mint':play.skin==='mint','mf-skin-berry':play.skin==='berry'}" dir="rtl" @keydown="onKey">
   <div class="mf-backdrop" aria-hidden="true"></div>
   <div class="mf-map" ref="map"><div class="mf-board" role="group" aria-label="רצפת מפעל תנופה">
    <img class="mf-ground" src="assets/momentum-factory/ground.png?v=213" alt="">
    <img class="mf-terrain" src="assets/momentum-factory/floor.png?v=213" alt="רצפת מפעל עם עמדות למכונות, צינורות ומעקות בטיחות">
    <img v-for="link in connections" :key="'link'+link.a+'-'+link.b" class="mf-link" :src="'assets/momentum-factory/link-'+link.a+'-'+link.b+'.png'" alt="">
    <div class="mf-world-sign" aria-hidden="true"><b>MY</b><span>FACTORY</span></div>
    <span v-if="art.supplySource" class="mf-source-label" :style="{left:art.supplySource.x+'%',top:(art.supplySource.y+2)+'%'}">יער העצים שלנו</span>
    <button class="mf-office" :style="anchorStyle(0)" aria-label="ניהול עובדים והזמנות" @click="selectOffice" :disabled="learning||phase==='opening'">משרד המפעל</button>
    <template v-for="(b,i) in factory.buildings"><button v-if="i>0&&(b||movingSite>=1||i===nextSite&&nextMachine)" :key="i" class="mf-site" :class="{'mf-guided':guide.site===i,'mf-empty':!b,'mf-building':!!b,'mf-pending':b&&b.pending,'mf-working':b&&isWorking(i)}" :style="siteStyle(i)" :data-site="i" :aria-label="b?types[b.type].name+' דרגה '+b.level:'מקום פנוי למכונה'" :disabled="learning||phase==='opening'||!!factory.outcome" @click="selectSite(i)"><img v-if="b" :src="'assets/momentum-factory/'+b.type+'-'+b.level+'.png'" alt=""><i v-if="b" class="mf-machine-meter" :style="{'--mf-fill':machineProgress(i)+'%'}" aria-hidden="true"></i><span v-if="b" class="mf-machine-motion" :style="machineStyle(b)" :data-machine="i"></span><span v-else aria-hidden="true">+<em>בונים כאן</em></span><small v-if="b">{{types[b.type].name}}<em>{{stationState(i).label}}</em></small></button></template>
    <template v-for="(b,i) in factory.buildings"><div v-if="b&&b.worker&&!workerWalking(i)" :key="'operator'+i" class="mf-operator" :data-operator="i" :style="{left:(art.anchors[i].x+8)+'%',top:(art.anchors[i].y+6)+'%',zIndex:Math.round(art.anchors[i].y)+7}" aria-hidden="true"><span class="mf-gait"></span></div></template>
    <div class="mf-operator mf-counter-worker" :style="{left:(art.exit.x+2)+'%',top:(art.exit.y+2)+'%',zIndex:Math.round(art.exit.y)+3}" aria-hidden="true"><span class="mf-gait"></span></div>
    <div v-for="j in factory.jobs" :key="'job'+j.site" class="mf-job" :data-job="j.site" aria-hidden="true"><span v-if="jobWalks(j)" class="mf-gait"></span><img class="mf-cargo" :src="'assets/momentum-factory/'+cargoFor(j)+'.png'" alt=""><span class="mf-task"></span></div>
    <template v-for="(b,i) in factory.buildings"><div v-if="b&&types[b.type].output" :key="'pile'+i" class="mf-pile" :data-pile="i" :style="pileStyle(i)"><img v-for="n in Math.min(12,stockTotal(types[b.type].output))" :key="n" :style="{left:((n-1)%3)*1.2+'cqw',bottom:Math.floor((n-1)/3)*.65+'cqw'}" :src="'assets/momentum-factory/'+resourceArt(types[b.type].output)+'.png'" alt=""><small>{{stockTotal(types[b.type].output)}}</small></div></template>
    <div class="mf-shop-stock" :style="{left:art.exit.x+'%',top:(art.exit.y-1)+'%'}"><img v-for="(lot,n) in market.counter" :key="n" :src="'assets/momentum-factory/'+resourceArt(lot.kind)+'.png'" :style="{left:(n%3)*1.1+'cqw',bottom:Math.floor(n/3)*.7+'cqw'}" alt=""></div>
    <div class="mf-porter mf-job" data-porter aria-hidden="true"><span class="mf-gait"></span><img v-if="market.porter&&market.porter.picked" class="mf-cargo" :src="'assets/momentum-factory/'+resourceArt(market.porter.kind)+'.png'" alt=""></div>
    <button @click="selectMarket" :disabled="!canManage" class="mf-shop-sign" :style="{left:(art.exit.x-10)+'%',top:(art.exit.y+3)+'%'}">חנות ומכירות</button>
    <div v-for="c in market.customers" :key="'customer'+c.slot" class="mf-customer" :data-customer="c.slot" aria-hidden="true"><span class="mf-gait"></span><img v-if="c.phase==='leaving'" class="mf-cargo" :src="'assets/momentum-factory/'+resourceArt(c.kind)+'.png'" alt=""><small>{{c.phase==='leaving'?'+'+c.paid: c.position===0?'קונה':'בתור'}}</small></div>
   <button v-if="play.special" class="mf-special-visitor" :style="{left:'52%',top:'74%'}" :disabled="!canManage" @click="openSpecial" aria-label="הזמנות מיוחדות של החברים"><img :src="'assets/momentum-factory/crew-'+(play.special&&play.special.kind==='parts'?'berry':'mint')+'.png'" alt=""><span>{{play.special?'מחכה להפתעה…':'יש לי בקשה!'}}</span></button>
   <div v-if="play.special" class="mf-special-courier mf-job" data-special-courier aria-hidden="true"><span class="mf-gait"></span><img v-if="play.special.picked" class="mf-cargo" :src="'assets/momentum-factory/'+resourceArt(play.special.kind)+'.png'" alt=""></div>
   <div v-if="notice&&notice.kind==='sale'" class="mf-sale-pop" :style="{left:art.exit.x+'%',top:(art.exit.y-5)+'%'}" :key="notice.key" aria-hidden="true">+{{notice.amount}} מטבעות<i v-for="n in 7" :key="n" :style="{'--n':n}"></i></div>
   </div></div>
   <header class="mf-top"><div class="mf-brand"><span class="mf-brand-gear" aria-hidden="true">✦</span><div><small>MY FACTORY</small><h1>מפעל תנופה</h1></div></div><div class="mf-wallet"><i aria-hidden="true">★</i><b>{{factory.points}}</b><span>כוכבי ידע</span></div><div class="mf-money"><i aria-hidden="true">●</i><b>{{factory.money}}</b><span>מטבעות</span></div><button class="mf-sound" :aria-label="play.sound?'השתקת צלילים':'הפעלת צלילים'" :aria-pressed="play.sound?'true':'false'" @click="toggleSound">{{play.sound?'♫':'♪'}}</button><button class="mf-exit" @click="exitGame">יציאה</button></header>
   <div v-if="factory.buildings.filter(Boolean).length<2" class="mf-stocks" aria-label="מלאי המפעל"><span v-for="(label,key) in resources" :key="key"><img :src="'assets/momentum-factory/'+resourceArt(key)+'.png'" alt=""><b>{{stockTotal(key)}}</b><small>{{label}}</small></span></div>
<button v-if="!learning&&phase!=='opening'" class="mf-view-toggle" @click="toggleOverview" :aria-pressed="overview?'true':'false'">{{overview?'מקרוב ＋':'כל המפעל −'}}</button>
   <section v-if="lineStations.length>=2&&!learning&&phase!=='opening'" class="mf-flow" aria-label="קו הייצור החי"><div class="mf-flow-heading"><b>{{phase==='running'?workingCount+' מכונות בתנועה':'הקו מחכה לכם'}}</b><span>כל מכונה עובדת בתור שלה, יחד עם האחרות</span></div><div class="mf-flow-stations"><button v-for="line in lineStations" :key="line.site" :class="{'is-moving':hasJob(line.site),'is-waiting':line.status.key==='input'||line.status.key==='worker'}" @click="selectSite(line.site)" :disabled="!canManage" :aria-label="types[line.b.type].name+': '+line.status.label"><img :src="'assets/momentum-factory/'+line.b.type+'-'+line.b.level+'.png'" alt=""><small>{{line.status.key==='input'?'מחכה לחומר':line.status.key==='worker'?'צריך עובד':line.status.key==='install'?'בבנייה':hasJob(line.site)?'עובדת':'מוכנה'}}</small><i :style="{'--mf-fill':machineProgress(line.site)+'%'}"></i></button></div></section>
   <section class="mf-order"><img :src="'assets/momentum-factory/crew-'+(['gold','mint','berry'][Math.min(2,factory.order)])+'.png'" alt=""><div><small>{{factory.endless?'כל ההזמנות הושלמו':'הזמנה '+Math.min(3,factory.order+1)+' מתוך 3'}}</small><b>{{contract.name}}</b><progress :value="factory.order>=3?contract.target:factory.delivered" :max="contract.target" aria-label="ארגזים שנמסרו"></progress><span><bdi dir="ltr">{{factory.order>=3?contract.target:factory.delivered}} / {{contract.target}}</bdi> ארגזים ללקוח</span></div></section>
   <button v-if="!learning&&phase!=='opening'&&!factory.outcome" class="mf-collection-open" @click="openCollection"><span aria-hidden="true">★</span><b>האוסף שלי</b><small dir="ltr">{{badges.filter(b=>b.unlocked).length}} / {{badges.length}}</small><i v-if="newBadges" aria-label="פרס חדש">!</i></button>
   <section v-if="!learning&&phase!=='opening'&&!factory.outcome&&selectedSite===-1" class="mf-guide" aria-label="המשימה הבאה">
    <img class="mf-guide-robot" :src="'assets/momentum-factory/crew-'+play.skin+'.png'" alt="מנהל המפעל, שמלווה אתכם"><div class="mf-guide-copy"><small>{{market.visits===1?'יש! הלקוח הראשון מרוצה!':'מנהל המפעל אומר'}}</small><h2>{{guide.title}}</h2><p>{{guide.text}}</p><div v-if="guide.cost" class="mf-goal"><progress :value="Math.min(factory.points,guide.cost)" :max="guide.cost" aria-label="כוכבים לקנייה הבאה"></progress><b>{{Math.min(factory.points,guide.cost)}} / {{guide.cost}} ★</b></div><button class="mf-primary mf-guide-action" :disabled="guide.action==='wait'&&phase==='running'" @click="followGuide">{{guideLabel}}</button></div>
   </section>
   <div v-if="notice&&(notice.kind==='badge'||notice.kind==='improved')&&!learning&&phase!=='opening'&&!factory.outcome" class="mf-toast" role="status"><img :src="'assets/momentum-factory/'+notice.art+'.png'" alt=""><div><small>{{notice.kind==='improved'?'השיפור שלכם בפעולה!':'הפתעה חדשה באוסף!'}}</small><b>{{notice.title}}</b></div><span class="mf-toast-star" aria-hidden="true">★</span></div>
   <footer class="mf-controls" v-if="!learning&&phase!=='opening'&&!factory.outcome"><p role="status">{{feedback||factory.event}}</p><div><button class="mf-primary mf-study" @click="openLearning"><b>★</b> מרוויחים כוכבים</button><button class="mf-turbo" :class="{'is-ready':play.energy===3,'is-active':play.boost>0}" :disabled="!!play.boost" @click="activateTurbo"><span aria-hidden="true">ϟ</span><b>{{play.boost?'טורבו!':play.energy===3?'טורבו מוכן!':'טוענים טורבו'}}</b><small dir="auto">{{play.boost?Math.ceil(play.boost/1000)+' שניות':play.energy+' / 3'}}</small></button><button class="mf-run" @click="toggleRun">{{phase==='running'?'Ⅱ עצירה':'▶ הפעלה'}}</button><button v-if="market.visits" class="mf-speed-open" @click="openSpeed">שיפור הקצב ↗</button><button class="mf-team" @click="selectOffice">הצוות</button><button class="mf-market" @click="selectMarket">החנות</button></div></footer>
   <section v-if="selectedSite===-6&&!learning&&phase!=='opening'" class="mf-dialog mf-context mf-speed-dialog" ref="context" tabindex="-1" role="dialog" aria-label="משפרים את קצב המפעל" @keydown.esc.stop="closeContext"><header><h2>יותר מהר, ביחד!</h2><button aria-label="סגירה" @click="closeContext">×</button></header>
    <template v-if="speed"><p>הצעד הבא שיעזור למפעל שלכם:</p><h3>{{speed.title}}</h3><div class="mf-speed-preview"><img :src="'assets/momentum-factory/'+factory.buildings[speed.site].type+'-'+factory.buildings[speed.site].level+'.png'" alt="המכונה עכשיו"><span aria-hidden="true">←</span><img :src="'assets/momentum-factory/'+(speed.action==='upgrade'?factory.buildings[speed.site].type+'-'+speed.after:speed.action==='conveyor'?'belt':'crew-gold')+'.png'" alt="השיפור הבא"></div><p>{{speed.text}}</p><p v-if="speed.cash&&factory.money<speed.cash" class="mf-speed-cash">עוד {{speed.cash-factory.money}} מטבעות מהמכירות. המפעל יכול להמשיך למכור בינתיים.</p><div class="mf-learning-goal"><span>כוכבים: <bdi dir="ltr">{{Math.min(factory.points,speed.cost)}} / {{speed.cost}}</bdi><template v-if="speed.cash"> · מטבעות: <bdi dir="ltr">{{Math.min(factory.money,speed.cash)}} / {{speed.cash}}</bdi></template></span><progress :value="Math.min(factory.points,speed.cost)" :max="Math.max(1,speed.cost)" aria-label="כוכבים לשיפור"></progress></div><button v-if="phase!=='running'&&speed.cash>factory.money" class="mf-speed-resume" @click="toggleRun">מפעילים את המפעל כדי להרוויח מטבעות</button><button class="mf-primary mf-speed-action" :disabled="factory.points>=speed.cost&&factory.money<speed.cash" @click="improveSpeed">{{speedLabel}}</button></template>
    <template v-else><img class="mf-speed-complete" src="assets/momentum-factory/assembly-3.png" alt=""><h3>{{factory.buildings.some(b=>b&&b.pending)?'השיפור כבר בדרך!':'כל המכונות מהירות ואוטומטיות!'}}</h3><p>הביטו בעובדים ובמשלוחים. כל התחנות ממשיכות לעבוד במקביל.</p></template><button class="mf-subtle" @click="closeContext">חזרה למפעל</button>
   </section>
   <section v-if="selectedSite===-3&&!learning&&phase!=='opening'" class="mf-dialog mf-context mf-collection" ref="context" tabindex="-1" role="dialog" aria-label="האוסף שלי" @keydown.esc.stop="closeContext"><header><div><small>כל פרס הוא משהו שבניתם באמת</small><h2>האוסף שלי</h2></div><button aria-label="סגירה" @click="closeContext">×</button></header><div class="mf-badge-grid"><button v-for="badge in badges" :key="badge.id" :class="{'is-locked':!badge.unlocked,'is-selected':badge.skin===play.skin}" :disabled="!badge.unlocked||!badge.skin" @click="chooseSkin(badge.skin)"><img :src="'assets/momentum-factory/'+badge.art+'.png'" alt=""><b>{{badge.name}}</b><small>{{badge.unlocked?badge.skin?(badge.skin===play.skin?'בצוות שלי':'בחרו אותי לצוות!'):badge.detail:badge.goal}}</small><span class="mf-badge-check">{{badge.unlocked?'✓':'?'}}</span></button></div><button class="mf-subtle" v-if="play.skin!=='gold'" @click="chooseSkin('gold')">מחזירים את העובד הזהוב</button></section>
   <section v-if="selectedSite===-4&&!learning&&phase!=='opening'" class="mf-dialog mf-context mf-special-dialog" ref="context" tabindex="-1" role="dialog" aria-label="הזמנות מהשכונה" @keydown.esc.stop="closeContext"><header><h2>הפתעות לשכונה</h2><button aria-label="סגירה" @click="closeContext">×</button></header><p>שולחים לחברים ומרוויחים יותר, או שומרים את החומרים למכונות. אתם בוחרים!</p><template v-if="play.special"><img class="mf-special-portrait" :src="'assets/momentum-factory/crew-'+specialOrders[play.special.kind].visitor+'.png'" alt="החבר שמחכה להזמנה"><h3>{{play.special.phase==='gather'?'שומרים חומרים לחבר':play.special.phase==='out'?'העובד אוסף את החומרים':play.special.phase==='carry'?'ההפתעה בדרך לחבר':'מוסרים את ההפתעה!'}}</h3><p v-if="play.special.phase==='gather'">המפעל מכין ושומר את החומרים להזמנה. העובד יאסוף אותם כשהכול מוכן.</p><progress :value="play.special.elapsed" :max="play.special.duration" aria-label="התקדמות ההזמנה"></progress><p>{{play.special.cash}} מטבעות יגיעו כשהחבר יקבל את ההפתעה.</p><button v-if="phase!=='running'" class="mf-primary" @click="toggleRun">ממשיכים במשלוח</button><button class="mf-subtle mf-special-cancel" @click="cancelDelivery">נשמור לפעם אחרת · החומרים נשארים</button></template><div v-else class="mf-special-choices"><article v-for="(request,kind) in specialOrders" :key="kind"><img :src="'assets/momentum-factory/crew-'+request.visitor+'.png'" alt=""><h3>{{request.name}}</h3><p><img :src="'assets/momentum-factory/'+request.art+'.png'" alt="">{{request.amount}} {{kind==='raw'?'עצים':'חלקים'}}</p><strong><bdi dir="ltr">+{{request.cash}}</bdi> מטבעות</strong><button class="mf-primary mf-special-send" :disabled="!canSendSpecial(kind)" @click="sendSpecial(kind)">{{canSendSpecial(kind)?specialReady(kind)?'שולחים לחבר!':'מכינים לחבר!':kind==='parts'?'קודם בונים מכבש':'קודם בונים מסוף'}}</button></article></div><small>{{play.deliveries}} הפתעות כבר הגיעו לחברים</small></section>
   <section v-if="selectedSite===-2&&!learning&&phase!=='opening'" class="mf-context mf-dialog" ref="context" tabindex="-1" role="dialog" aria-label="חנות ומכירות" @keydown.esc.stop="closeContext"><header><h2>חנות ומכירות</h2><button aria-label="סגירה" @click="closeContext">×</button></header><p>הלקוחות קונים מהמלאי. אפשר להתחיל במכירת חומרי גלם לפני שבונים את כל המפעל.</p>
    <button v-if="market.visits" class="mf-special-entry" @click="openSpecial"><img src="assets/momentum-factory/crew-mint.png" alt=""><span><b>הזמנה נוספת, לבחירתכם</b><small>המכירה הרגילה ממשיכה לבד</small></span></button><h3>מכירה אוטומטית</h3><p>שליח מביא מוצרים מוכנים לחנות, והמוכר משרת את הלקוחות לבד. לא צריך לאשר בקשות. כשיש מכונת אריזה, נשמרים לה חומרים להמשך הייצור.</p><button v-if="!supplyStation" class="mf-first-supply" :disabled="factory.points<buildCosts.supply||!canManage" @click="buildFirstSupply">בניית מחסן העצים · {{buildCosts.supply}} כוכבים</button><p v-else>{{supplyStation.pending?'המסוף בהתקנה — הפעילו את המפעל להשלמתה':supplyStation.worker||supplyStation.level>=2?'אספקת חומרי הגלם אוטומטית':'המסוף מוכן — שייכו אליו עובד לאספקה רציפה'}}</p>
    <button v-if="supplyStation&&!supplyStation.worker&&supplyStation.level<2" class="mf-supply-worker" :disabled="supplyStation.pending||!canManage||!spareEmployee" @click="assignSupply">שיוך עובד למסוף</button><p v-if="supplyStation&&!supplyStation.worker&&!spareEmployee">כל העובדים משויכים. אפשר לשחרר עובד מתחנה אחרת או לגייס במשרד.</p>
    <button v-for="kind in ['raw','parts']" :key="kind" class="mf-outlet" :disabled="(!market.outlets[kind]&&factory.points<outletCosts[kind])||!canManage" @click="unlockOutlet(kind)">{{market.outlets[kind]?(market.paused[kind]?'חידוש מכירת ':'השהיית מכירת '):'פתיחת מכירת '}}{{resources[kind]}}{{market.outlets[kind]?'':' · '+outletCosts[kind]+' כוכבים'}}</button>
    <button class="mf-primary mf-shop-run" v-if="phase!=='running'" :disabled="!canManage" @click="toggleRun">הפעלת המפעל והמכירות</button><p v-else>המפעל פועל. הלקוחות מקבלים סחורה ומשלמים כשהמלאי מוכן.</p><p>מלאי: {{stockTotal('raw')}} עצים · {{stockTotal('parts')}} חלקים · {{stockTotal('products')}} מוצרים מוכנים · {{stockTotal('boxes')}} ארגזים.</p><p>{{market.visits}} קונים מרוצים · {{market.revenue||0}} מטבעות ממכירות.</p><p>צעצועים נמכרים ישירות ממכונת ההרכבה. כדי למלא את הזמנת הארגזים, הוסיפו אריזה ומשלוחים.</p></section>
   <section v-if="selectedSite>=1&&!learning&&phase!=='opening'" class="mf-context mf-dialog" ref="context" tabindex="-1" role="dialog" aria-label="ניהול תחנה" @keydown.esc.stop="closeContext"><header><h2>{{selected?types[selected.type].name:'איזו תחנה מוסיפים?'}}</h2><button aria-label="סגירה" @click="closeContext">×</button></header>
    <template v-if="selected"><p>{{types[selected.type].detail}}</p><p>דרגה {{selected.level}} · {{selected.pending?'ההתקנה תושלם כשהמפעל פועל':selected.level>=2?'אוטומציה פעילה':'שייכו עובד לאוטומציה, או הפעילו מחזור ידני'}}</p><p class="mf-station-status">עכשיו: {{stationState(selectedSite).label}}</p><button v-if="stationState(selectedSite).key==='input'&&stationState(selectedSite).source>0" class="mf-trace-source" @click="selectSite(stationState(selectedSite).source)">למכונה שמכינה את החומר ←</button><p class="mf-rate">עד {{selected.level}} יחידות במחזור · עיבוד {{processingSeconds(selected)}} שניות</p><button v-if="selected.level<3" class="mf-upgrade" :disabled="!canUpgrade()" @click="upgradeSelected">{{selected.level===1?(selected.type==='supply'?'איסוף מהיר יותר':'אוטומציה + מסוע + ייצור מהיר יותר'):'תפוקה גדולה יותר + ייצור מדויק'}} · {{upgradePrice()}} כוכבים + {{upgradeCash()}} מטבעות</button><button v-if="selected.type!=='supply'&&!stationHasConveyor(selected)" class="mf-buy-conveyor" :disabled="!canManage||selected.pending||factory.money<10" @click="buySelectedConveyor">קונים מסוע · 10 מטבעות</button><p v-if="selected.type!=='supply'">{{stationHasConveyor(selected)?'המסוע מביא חומרים. העובד מפעיל את המכונה.':'כרגע העובד מביא חומרים. מסוע יקצר את ההעברה ביותר מחצי!'}}</p><button class="mf-assign" :disabled="!canAssign()" @click="assignSelected">{{selected.worker?'שחרור העובד לתחנה אחרת':'שיוך עובד לתחנה'}}</button><button v-if="selected.level===1&&!selected.worker" class="mf-manual" :disabled="selected.pending||hasJob(selectedSite)||selected.manual" @click="manualSelected">הפעלת מחזור אחד</button><button class="mf-subtle" :disabled="!canManage||!!selected.pending" @click="beginMove">העברת התחנה למקום פנוי · ללא עלות</button></template>
    <div v-else class="mf-blueprints"><button v-for="(t,key) in visibleTypes" :key="key" :disabled="!canBuy(key)" @click="buySelected(key)"><img :src="'assets/momentum-factory/'+key+'-1.png'" alt=""><span><b>{{t.name}}</b><small>{{buildCosts[key]}} כוכבי ידע</small></span></button><p v-if="factory.buildings.filter(Boolean).length===5">כל התחנות כבר במפעל. המקום הפנוי מאפשר להעביר תחנה ולשנות את סידור הקו.</p></div>
   </section>
   <section v-if="selectedSite===0&&!learning&&phase!=='opening'" class="mf-dialog mf-context" ref="context" tabindex="-1" role="dialog" aria-label="עובדים והזמנות" @keydown.esc.stop="closeContext"><header><h2>משרד המפעל</h2><button aria-label="סגירה" @click="closeContext">×</button></header><p>עובדים משויכים: <bdi dir="ltr">{{workers}}</bdi>. עובד מפעיל תחנה ברצף ומאיץ את הייצור. בהתחלה העובד מביא גם חומרים. קונים מסועים ב־10 מטבעות כדי לחבר בין מכונות ולהאיץ את העבודה. מול הלקוחות עובדים אנשים.</p><button class="mf-primary mf-hire" :disabled="factory.points<5||factory.employees===5||!canManage" @click="hireWorker">{{factory.employees===5?'כל הצוות כבר כאן':'גיוס עובד · 5 כוכבים'}}</button><h3>אפיקי הכנסה נוספים</h3><p>מכרו חומרי גלם וחלקים ישירות ללקוחות, במקביל למוצרים המוגמרים. כל אפיק משתמש במלאי המפעל.</p><button v-for="kind in ['raw','parts']" :key="kind" class="mf-outlet" :disabled="(!market.outlets[kind]&&factory.points<outletCosts[kind])||!canManage" @click="unlockOutlet(kind)">{{resources[kind]}} · {{market.outlets[kind]?(market.paused[kind]?'חידוש המכירה':'השהיית המכירה'):outletCosts[kind]+' כוכבים לפתיחה'}}</button><h3>{{contract.name}}</h3><p>ספקו {{contract.target}} {{contract.product}}. המכירה נספרת רק כשהמטען מגיע ללקוח.</p><p>הקו מייצר לפי התחנה הפחות משודרגת. שדרגו את כל התחנות לדרגה {{contract.grade}} כדי לייצר את המוצר המבוקש.</p><p>דרגה 2 מוסיפה אוטומציה. דרגה 3 מאיצה ופותחת ייצור מדויק. אפשר להמשיך למכור מוצרים פשוטים כדי לממן שדרוגים.</p><p>אין הפסד של מבנים או ידע. שיוך עובדים והעברת תחנות הם ללא עלות.</p></section>
   <section v-if="phase==='opening'||learning||factory.outcome" class="mf-dialog mf-overlay" role="dialog" :aria-label="learning?'לומדים במפעל':'יומן המפעל'" @keydown.esc.stop="returnToFactory">
    <template v-if="newWords.length"><small>מילים חדשות · <bdi dir="ltr">{{newWordIndex+1}} / {{newWords.length}}</bdi></small><h2 ref="wordHeading" tabindex="-1" dir="auto" v-html="newWordContent().question"></h2><div class="mf-translation" dir="auto" v-html="newWordContent().result"></div><p>הייצור מושהה. מכירים את המילה וממשיכים.</p><button class="mf-primary mf-news-next" @click="nextNewWord">{{newWordIndex+1===newWords.length?'מתחילים לתרגל':'למילה הבאה'}}</button></template>
    <template v-else-if="phase==='opening'"><div class="mf-welcome-art"><img src="assets/momentum-factory/supply-1.png" alt="מחסן העצים הראשון שנבנה"><span class="mf-welcome-star" aria-hidden="true">✦</span></div><small class="mf-kicker">MY FACTORY</small><h2>בואו נפתח מפעל!</h2><p>נתחיל ב־3 שאלות ונבנה מחסן עצים.<br>העובד יאסוף לבד. אנחנו נוסיף עוד מכונות!</p><button class="mf-primary mf-start" @click="startGame">בואו נשחק! <span aria-hidden="true">◀</span></button><small>לומדים ← בונים ← המפעל עובד בשבילנו</small></template>
    <template v-else-if="factory.outcome"><div class="mf-victory-art"><img :src="'assets/momentum-factory/crew-'+(factory.order===1?'mint':factory.order===2?'berry':play.skin)+'.png'" alt="דמות חדשה באוסף"><span aria-hidden="true">★ ★ ★</span></div><small>{{factory.outcome==='victory'?'מפעל העתיד מוכן':'עוד לקוח מרוצה'}}</small><h2>{{factory.outcome==='victory'?'זה מפעל החלומות שלנו!':factory.order===1?'הצוות הירוק מצטרף לצוות!':'הכירו את הצוות הסגול!'}}</h2><p>{{factory.event}}</p><p v-if="factory.outcome==='victory'">חומרי הגלם מגיעים, המכונות מייצרות והמשלוחים נמכרים. הלמידה שלכם הפכה בית מלאכה למפעל אוטומטי.</p><button class="mf-primary mf-next-order" @click="advanceOrder">{{factory.outcome==='victory'?'ממשיכים לייצר ולמכור':'פותחים את השוק הבא'}}</button></template>
    <template v-else><div class="mf-learning-header"><img :src="'assets/momentum-factory/crew-'+play.skin+'.png'" alt=""><div><small>סדנת ההמצאות של המפעל</small><b>כל תשובה מקרבת את ההפתעה הבאה</b></div><span class="mf-learning-energy" dir="ltr">ϟ {{play.energy}} / 3</span></div><div class="mf-learning-goal" v-if="practiceGoal.cost"><b>{{practiceGoal.title}}</b><span>{{practiceRemaining?'עוד '+practiceRemaining+' תשובות נכונות ונוכל לקנות!':'יש מספיק כוכבים! אפשר לחזור למפעל ולבנות.'}}</span><progress :value="Math.min(factory.points,practiceGoal.cost)" :max="practiceGoal.cost" aria-label="כוכבים לקנייה"></progress></div><small>כל תשובה נכונה מוסיפה כוכב ידע וטוענת את הטורבו · המפעל מחכה לכם</small><h2 ref="questionHeading" tabindex="-1" dir="auto" v-html="question&&question.question"></h2><div class="mf-answers"><button v-for="(option,i) in options" :key="i" :disabled="phase!=='ready'" :class="{'mf-wrong':wrongIndex===i}" @click="answer(i)"><kbd>{{i+1}}</kbd><span dir="auto" v-html="option"></span></button></div><p role="status" aria-live="polite" :class="{'mf-success':phase==='resolved'}">{{feedback}}</p><button v-if="phase==='retry'" class="mf-retry" @click="retry">ננסה שוב את אותה שאלה</button><button class="mf-return" :class="{'mf-primary':practiceGoal.cost&&practiceRemaining===0}" @click="returnToFactory">{{practiceGoal.cost&&practiceRemaining===0?'יש מספיק כוכבים! חוזרים למפעל':'חזרה למפעל'}}</button></template>
   </section>
   <span class="mf-credit">KayKit + Kenney · CC0</span>
  </main>`,
  methods:{
   sound(kind){
    if(!this.play.sound||this.hidden||this.stopped)return;
    const Audio=global.AudioContext||global.webkitAudioContext;if(!Audio)return;
    try{if(!this._mfAudio)this._mfAudio=new Audio();const a=this._mfAudio;if(a.state==='suspended')a.resume().catch(()=>{});
     const notes={correct:[523,659,784],build:[330,440,660],sale:[784,1047],boost:[262,392,523,784],badge:[523,659,784,1047]};
     (notes[kind]||notes.build).forEach((hz,i)=>{const o=a.createOscillator(),g=a.createGain(),at=a.currentTime+i*.075;o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.045,at+.012);g.gain.exponentialRampToValueAtTime(.001,at+.19);o.connect(g);g.connect(a.destination);o.start(at);o.stop(at+.2);o.onended=()=>{o.disconnect();g.disconnect();};});
    }catch(e){/* Audio is optional; a blocked device never blocks play. */}
   },
   toggleSound(){this.play.sound=!this.play.sound;if(this.play.sound)this.sound('correct');else if(this._mfAudio)this._mfAudio.suspend().catch(()=>{});this.save();},
   activateTurbo(){if(!this.canManage)return;if(this.play.energy<3){this.openLearning();return;}if(this.phase!=='running')this.toggleRun();if(boost(this.factory)){this.sound('boost');this.save();}},
   openCollection(){if(!this.canManage)return;this.selectedSite=-3;this.play.seen=this.badges.filter(b=>b.unlocked).map(b=>b.id);this.notice=null;this.save();this.focus('context');},
   stationHasConveyor:hasConveyor,jobWalks:walks,workerWalking(site){return this.factory.jobs.some(j=>j.site===site&&walks(j));},
   buySelectedConveyor(){if(this.canManage&&buyConveyor(this.factory,this.selectedSite)){this.sound('build');this.save();this.closeContext();}},
   paintWalker(el,a,b,moving=true){const g=el.querySelector('.mf-gait');if(!g)return;/* Atlas rows: front, front-right, right, back, left, front-left. */const angle=Math.atan2(b.y-a.y,b.x-a.x),row=((Math.round((Math.PI/2-angle)/(Math.PI/3))%6)+6)%6;g.style.backgroundPosition=(moving&&!this.reduced?Math.floor((this.factory.time+this.clock().elapsed)%this.art.worker.duration/this.art.worker.duration*24)/23*100:0)+'% '+row*20+'%';},
   stationState(site){return stationStatus(this.factory,site);},
   openSpeed(){if(this.canManage){this.selectedSite=-6;this.focus('context');}},
   improveSpeed(){if(!this.canManage||this.selectedSite!==-6||!this.speed)return;if(this.factory.points<this.speed.cost){const target={...this.speed};this.openLearning();this.practiceTarget=target;return;}if(applySpeed(this.factory)){if(this.phase!=='running')this.toggleRun();this.sound('build');this.save();this.closeContext();}},
   toggleOverview(){this.overview=!this.overview;this.fitMap();},
   cancelDelivery(){if(this.canManage&&cancelSpecial(this.factory)){this.save();this.closeContext();}},
   openSpecial(){if(this.canManage&&this.market.visits){this.selectedSite=-4;this.focus('context');}},
   specialReady(kind){return specialGrade(this.factory,kind)>0;},
   canSendSpecial(kind){return this.canManage&&canSpecial(this.factory,kind);},
   sendSpecial(kind){if(this.canManage&&startSpecial(this.factory,kind)){if(this.phase!=='running')this.toggleRun();this.sound('build');this.save();this.closeContext();}},
   chooseSkin(skin){if(this.canManage&&setSkin(this.factory,skin)){this.sound('build');this.save();}},
   machineProgress(i){const b=this.factory.buildings[i];if(!b)return 0;if(b.pending)return (1-b.pending/3000)*100;const j=this.factory.jobs.find(j=>j.site===i);return j?j.elapsed/j.duration*100:0;},
   checkMoments(){const c=this.clock(),ids=this.badges.filter(b=>b.unlocked).map(b=>b.id);if(c.badges){const newId=ids.find(id=>!c.badges.includes(id));if(newId){const b=BADGES.find(b=>b.id===newId);this.notice={kind:'badge',title:b.name,art:b.art,key:this.factory.time,until:this.factory.time+5500};this.sound('badge');}}
    if(c.visits!==undefined&&this.market.visits>c.visits&&(!this.notice||!['badge','improved'].includes(this.notice.kind))){const r=this.market.receipts[this.market.receipts.length-1];this.notice={kind:'sale',amount:r?r.amount:0,key:this.factory.time,until:this.factory.time+2000};this.sound('sale');}
    const ready=this.factory.buildings.map(b=>b&&!b.pending?b.level:0);if(c.readyLevels){const site=ready.findIndex((level,i)=>level>1&&level>c.readyLevels[i]);if(site>0&&(!this.notice||this.notice.kind!=='badge')){const b=this.factory.buildings[site];this.notice={kind:'improved',title:TYPES[b.type].name+' מייצרת יותר בכל סיבוב!',art:b.type+'-'+b.level,key:this.factory.time,until:this.factory.time+4500};this.sound('build');}}c.readyLevels=ready;
    c.badges=ids;c.visits=this.market.visits;if(this.notice&&this.factory.time>this.notice.until)this.notice=null;
   },
   followGuide(){
    if(!this.canManage)return;const g=this.guide;
    if(this.guideRemaining){this.openLearning();return;}
    if(g.action==='build'){this.sound('build');}if(g.action==='build'&&guidedBuild(this.factory,g.site,g.type)){this.phase='running';this.clock().last=null;}
    else if(g.action==='assign')assign(this.factory,g.site);
    else if(g.action==='hire'&&hire(this.factory))assign(this.factory,g.site);
    else if(g.action==='outlet')openOutlet(this.factory,'raw');
    else if(g.action==='resume')this.$set(this.market.paused,'raw',false);
    else if(g.action==='upgrade')upgrade(this.factory,g.site);
    else if(g.action==='wait'&&this.phase!=='running')this.toggleRun();
    this.checkMoments();this.save();
   },
   clock(){if(!this._mfClock)this._mfClock={last:null,raf:null,save:0,feedback:0,elapsed:0};return this._mfClock;},
   key(){return this.currentAppId+'_MomentumFactory_v1';},
   save(){if(!this.currentAppId)return;setLocalStorage(this.key(),{version:1,factory:copy(this.factory),opening:this.phase==='opening',elapsed:this.clock().elapsed});},
   restore(){const saved=getLocalStorage(this.key(),null);if(saved&&saved.version===1&&saved.factory&&saved.factory.buildings.length===7){prepareMarket(saved.factory);preparePlay(saved.factory);this.factory=saved.factory;this.clock().elapsed=saved.elapsed||0;this.phase=saved.opening?'opening':'planning';}else{const factory=fresh();prepareMarket(factory);preparePlay(factory);this.factory=factory;this.phase='opening';this.clock().elapsed=0;}this.resumePhase='planning';this.clock().badges=null;this.clock().readyLevels=null;this.notice=null;this.checkMoments();},
   focus(ref){this.$nextTick(()=>{if(!this.stopped&&this.$refs[ref])this.$refs[ref].focus({preventScroll:true});});},
   startGame(){if(this.phase==='opening'){this.phase='planning';this.sound('build');this.save();}},
   toggleRun(){if(this.learning||this.factory.outcome)return;this.phase=this.phase==='running'?'planning':'running';this.factory.started=true;this.clock().last=null;this.save();},
   selectMarket(){this.selectedSite=-2;this.focus('context');},
   buildFirstSupply(){if(this.canManage){const site=this.factory.buildings.findIndex((b,i)=>i>0&&!b);buy(this.factory,site,'supply');this.save();}},
   assignSupply(){if(this.canManage&&this.spareEmployee){assign(this.factory,siteOf(this.factory,'supply'));this.save();}},
   selectOffice(){this.selectedSite=0;this.focus('context');},
   selectSite(i){if(this.learning)return;if(this.movingSite>=0&&!this.factory.buildings[i]){relocate(this.factory,this.movingSite,i);this.movingSite=-1;this.feedback='';this.save();return;}this.selectedSite=i;this.focus('context');},
   closeContext(){const i=this.selectedSite;this.selectedSite=-1;this.$nextTick(()=>{const b=this.$el.querySelector('[data-site="'+i+'"]');if(b)b.focus({preventScroll:true});});},
   canBuy(type){return this.canManage&&!this.selected&&this.factory.points>=BUILD_COSTS[type]&&type===this.nextMachine&&!building(this.factory,type);},
   buySelected(type){if(this.canManage&&buy(this.factory,this.selectedSite,type)){this.sound('build');this.checkMoments();this.save();this.closeContext();}},
   canUpgrade(){const b=this.selected;return this.canManage&&b&&!b.pending&&b.level<3&&this.factory.points>=PRICES[b.level]&&this.factory.money>=CASH[b.level];},
   upgradePrice(){return this.selected?PRICES[this.selected.level]:0;},upgradeCash(){return this.selected?CASH[this.selected.level]:0;},
   upgradeSelected(){if(this.canManage&&upgrade(this.factory,this.selectedSite)){this.sound('build');this.checkMoments();this.save();this.closeContext();}},
   canAssign(){return this.canManage&&this.selected&&!this.selected.pending&&(this.selected.worker||assigned(this.factory)<this.factory.employees);},
   assignSelected(){if(this.canManage&&assign(this.factory,this.selectedSite))this.save();},
   hireWorker(){if(this.canManage&&hire(this.factory)){this.sound('build');this.checkMoments();this.save();}},
   manualSelected(){if(this.canManage&&manual(this.factory,this.selectedSite)){this.phase='running';this.clock().last=null;this.save();this.closeContext();}},
   beginMove(){this.movingSite=this.selectedSite;this.feedback='בחרו מקום פנוי להעברת התחנה';this.closeContext();},
   unlockOutlet(kind){if(this.market.outlets[kind])this.$set(this.market.paused,kind,!this.market.paused[kind]);else openOutlet(this.factory,kind);this.save();},
   advanceOrder(){if(this.factory.outcome==='victory'){keepTrading(this.factory);this.phase='running';this.save();return;}nextOrder(this.factory);this.phase='planning';this.save();},
   stockTotal(key){return total(this.factory,key);},processingSeconds(b){return (duration(b,'work')/1000).toFixed(1);},hasJob(site){return this.factory.jobs.some(j=>j.site===site);},isWorking(site){return this.factory.jobs.some(j=>j.site===site&&j.phase==='work');},
   anchorStyle(i){const p=this.art.anchors[i];return {left:p.x+'%',top:p.y+'%'};},
   siteStyle(i){const b=this.factory.buildings[i],p=this.art.anchors[i];if(!b)return {left:p.x+'%',top:p.y+'%'};const a=this.art.sprites[b.type+'-'+b.level];return {left:(p.x+a.dx)+'%',top:(p.y+a.dy)+'%',width:a.w+'%',height:a.h+'%',zIndex:Math.round(p.y)};},
   machineStyle(b){return {backgroundImage:'url(assets/momentum-factory/'+b.type+'-'+b.level+'-work.png)'};},
   resourceArt(kind){return {raw:'raw',parts:'part',products:'product',boxes:'box'}[kind]||'box';},
   pileStyle(i){const p=this.art.anchors[i];return {left:(p.x+4)+'%',top:(p.y+3)+'%',zIndex:Math.round(p.y+3)};},
   cargoFor(j){return j.phase==='delivery'?'box':({raw:'raw',parts:'part',products:'product',boxes:'box'}[j.input]||'raw');},
   paint(){if(!this.$el)return;const art=this.art,c=this.clock(),speed=this.play.boost>0?2:1;const m=prepareMarket(this.factory);for(const el of this.$el.querySelectorAll('[data-operator]')){const job=this.factory.jobs.find(j=>j.site===Number(el.dataset.operator)),gait=el.querySelector('.mf-gait'),working=job&&job.phase==='work';gait.classList.toggle('mf-task-gait',!!working);gait.style.backgroundPosition=(working&&!this.reduced?Math.floor((job.elapsed+c.elapsed*speed)%art.worker.duration/art.worker.duration*24)/23*100:0)+'% 0';}for(const buyer of m.customers){const el=this.$el.querySelector('[data-customer="'+buyer.slot+'"]');if(!el)continue;const t=this.reduced?1:Math.min(1,(buyer.elapsed+c.elapsed*speed)/buyer.duration),q=buyer.phase==='moving'?buyer.from+(buyer.target-buyer.from)*t:buyer.position,out=buyer.phase==='leaving'?t*17:0,x=art.exit.x+q*2.9-out,y=art.exit.y+4+q*1.8+out*.4;el.style.transform='translate('+x+'cqw,'+y+'cqw)';el.style.zIndex=Math.round(y)+2;el.querySelector('.mf-gait').style.backgroundPosition=(buyer.phase==='waiting'||this.reduced?0:Math.floor((this.factory.time+c.elapsed*speed)%art.worker.duration/art.worker.duration*24)/23*100)+'% '+(buyer.phase==='leaving'?60:80)+'%';}
    const porter=this.$el.querySelector('[data-porter]');if(porter){const p=m.porter,source=p?art.anchors[p.source]:art.exit,a=p&&p.phase==='out'?art.exit:source,b=p&&p.phase==='out'?source:art.exit,t=p?Math.min(1,(p.elapsed+c.elapsed*speed)/p.duration):1,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;porter.style.transform='translate('+x+'cqw,'+y+'cqw)';porter.style.zIndex=Math.round(y)+2;this.paintWalker(porter,a,b,!!p);}
   const courier=this.$el.querySelector('[data-special-courier]');if(courier&&this.play.special){const p=this.play.special,source=art.anchors[p.source],home=art.exit,a=p.phase==='out'?home:source,b=p.phase==='out'?source:home,t=['handoff','gather'].includes(p.phase)?1:Math.min(1,(p.elapsed+c.elapsed*speed)/p.duration),x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;courier.style.transform='translate('+x+'cqw,'+y+'cqw)';courier.style.zIndex=Math.round(y)+2;this.paintWalker(courier,a,b,!['handoff','gather'].includes(p.phase));}
   for(const j of this.factory.jobs){const el=this.$el.querySelector('[data-job="'+j.site+'"]');if(!el)continue;const at=art.anchors[j.site],source=j.type==='supply'?(art.supplySource||art.anchors[0]):art.anchors[j.source],a=j.phase==='out'?at:j.phase==='fetch'?source:at,b=j.phase==='out'?source:j.phase==='delivery'?art.exit:at,t=this.reduced?1:Math.min(1,(j.elapsed+c.elapsed*speed)/j.duration),x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;el.style.transform='translate('+x+'cqw,'+y+'cqw)';el.style.zIndex=Math.round(y)+1;this.paintWalker(el,a,b);
    el.querySelector('.mf-cargo').style.display=['fetch','delivery'].includes(j.phase)?'block':'none';el.querySelector('.mf-task').textContent=j.phase==='delivery'?'ללקוח':'';
    const machine=this.$el.querySelector('[data-machine="'+j.site+'"]');if(machine)machine.style.backgroundPosition=(this.reduced?0:Math.floor((j.elapsed+c.elapsed*speed)%1500/1500*16)/15*100)+'% 0';
   }},
   startFrames(){const c=this.clock();if(c.raf!==null||this.stopped||this.hidden)return;const frame=now=>{c.raf=null;if(this.stopped)return;const dt=c.last===null?0:Math.min(100,Math.max(0,now-c.last));c.last=now;if(!this.hidden){if(this.phase==='running'&&!this.newWords.length){c.elapsed+=dt;let changed=false;while(c.elapsed>=100){changed=step(this.factory,100)||changed;c.elapsed-=100;}if(changed){this.revision++;this.save();}this.paint();this.checkMoments();if(this.factory.outcome){this.phase='planning';this.selectedSite=-1;this.save();}}if(this.phase==='resolved'&&!this.newWords.length){c.feedback=Math.max(0,c.feedback-dt);if(!c.feedback){this.question=null;if(this.practiceTarget&&this.factory.points>=this.practiceTarget.cost)this.returnToFactory();else this.create();}}c.save+=dt;if(c.save>=1000){c.save=0;if(this.phase==='running')this.save();}}c.raf=global.requestAnimationFrame(frame);};c.raf=global.requestAnimationFrame(frame);},
   openLearning(){this.practiceTarget=null;if(this.stopped||this.factory.outcome||this.phase==='opening')return;this.selectedSite=-1;this.resumePhase=this.phase==='running'?'running':'planning';this.phase=this.question?(this.wrongIndex>=0?'retry':'ready'):'ready';this.clock().last=null;if(!this.question)this.create();else this.focus('questionHeading');this.save();},
   create(){if(this.stopped||this.newWords.length||!['ready','resolved'].includes(this.phase))return;if(!this.reloadProgress()){if(!this.newWords.length)this.phase='completed';return;}const a=this.currentApp;this.question=generateFromList(a.listName,a.questionIndex,a.resultIndex,this.currentAppId,getSetItems(a),a.questionType);this.questionIndex=this.question.questionIndex;this.options=this.shuffle(this.question.options.slice());if(!this.reloadProgress()){if(!this.newWords.length)this.phase='completed';return;}this.phase='ready';this.wrongIndex=-1;this.feedback='';if(this.question.action)this.question.action();this.focus('questionHeading');},
   answer(i){if(this.stopped||this.hidden||this.newWords.length||this.phase!=='ready'||!this.question||!Number.isInteger(i)||i<0||i>=this.options.length)return;this.phase='resolved';if(this.options[i]!==this.question.result){this.score=Math.max(0,this.score-1);this.saveScore();updateWeightForKey(this.currentAppId,this.questionIndex,1);this.wrongIndex=i;this.feedback='עוד ניסיון — הכוכבים והמפעל נשמרים.';if(!this.reloadProgress()){if(!this.newWords.length)this.phase='completed';return;}this.phase='retry';return;}
    updateWeightForKey(this.currentAppId,this.questionIndex,-1);this.score++;reward(this.factory);this.save();const keep=this.reloadProgress();this.saveScore();if(!keep){if(!this.newWords.length)this.phase='completed';return;}this.sound('correct');this.feedback='מעולה! +1 כוכב ידע ★'+(this.play.energy===3?' · הטורבו מוכן!':'');this.clock().feedback=700;
   },
   retry(){if(this.phase==='retry'&&!this.stopped){this.phase='ready';this.wrongIndex=-1;this.feedback='';this.focus('questionHeading');}},
   returnToFactory(){if(this.newWords.length||!this.learning)return;if(this.phase==='resolved'){this.question=null;this.options=[];}this.phase=this.resumePhase;this.feedback='';this.clock().last=null;if(this.practiceTarget){this.selectedSite=-6;this.practiceTarget=null;this.focus('context');}this.save();this.$nextTick(()=>{const b=this.selectedSite===-6?this.$refs.context:this.$el.querySelector('.mf-study');if(b)b.focus();});},
   presentNewItems(){if(this.newWords.length)return;if(!this.learning)this.resumePhase=this.phase==='running'?'running':'planning';this.newWords=getLocalStorage(this.currentAppId+'_new_items',[]).slice();this.newWordIndex=0;this.selectedSite=-1;this.clock().last=null;this.$nextTick(()=>this.speakNewWord());},
   newWordContent(){const item=getDataList(this.currentApp.listName)[this.newWords[this.newWordIndex]];if(!item)return {question:'',result:''};const q={...item[this.currentApp.questionIndex]};if(this.currentApp.questionType)q.type=this.currentApp.questionType;return {question:render(q),result:render(item[this.currentApp.resultIndex]),source:q};},
   speakNewWord(){if(this.stopped)return;const c=this.newWordContent();if(c.source)generateQuestion(c.source)();this.focus('wordHeading');},
   nextNewWord(){if(!this.newWords.length)return;if(this.newWordIndex+1<this.newWords.length){this.newWordIndex++;this.speakNewWord();return;}setLocalStorage(this.currentAppId+'_new_items',[]);this.newWords=[];this.question=null;this.options=[];this.phase='ready';this.create();},
   visibility(){this.hidden=document.hidden;const c=this.clock();c.last=null;if(this.hidden){if(this._mfAudio)this._mfAudio.suspend().catch(()=>{});if(c.raf!==null)global.cancelAnimationFrame(c.raf);c.raf=null;this.save();}else this.startFrames();},
   fitMap(){this.$nextTick(()=>{if(this.$refs.map)this.$refs.map.scrollLeft=Math.max(0,(this.$refs.map.querySelector('.mf-board').clientWidth-this.$refs.map.clientWidth)/2-(this.overview?0:45));this.paint();});},
   onKey(e){if(e.key==='Tab'){const dialog=this.$el.querySelector('.mf-overlay')||this.$el.querySelector('.mf-context');if(dialog){const items=[...dialog.querySelectorAll('button:not(:disabled),[tabindex="0"],a[href]')];if(items.length&&((e.shiftKey&&document.activeElement===items[0])||(!e.shiftKey&&document.activeElement===items[items.length-1]))){e.preventDefault();items[e.shiftKey?items.length-1:0].focus();return;}}}if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(/^[1-4]$/.test(e.key)&&this.phase==='ready'){e.preventDefault();this.answer(Number(e.key)-1);}},
   exitGame(){this.save();this.phase='completed';this.$router.push('/app/'+this.currentAppId);}
  },
  mounted(){this.restore();this._mfMedia=global.matchMedia&&global.matchMedia('(prefers-reduced-motion: reduce)');this.reduced=!!(this._mfMedia&&this._mfMedia.matches);this._mfReduced=event=>{this.reduced=event.matches;this.paint();};if(this._mfMedia&&this._mfMedia.addEventListener)this._mfMedia.addEventListener('change',this._mfReduced);this.visibility();this.fitMap();document.addEventListener('visibilitychange',this.visibility);global.addEventListener('resize',this.fitMap);this.startFrames();},
  watch:{'$route.params.currentAppId'(id){if(!id||id===this.currentAppId)return;this.save();this.practiceTarget=null;this.newWords=[];this.question=null;this.options=[];this.selectedSite=-1;this.movingSite=-1;this.feedback='';this.wrongIndex=-1;if(global.speechSynthesis)global.speechSynthesis.cancel();this.currentAppId=id;this.currentApp=getItemById(apps,id);this.restore();this.clock().last=null;this.clock().feedback=0;this.updateScore();this.reloadProgress();this.saveApp(id);}},
  beforeDestroy(){this.save();this.stopped=true;if(this._mfAudio)this._mfAudio.close().catch(()=>{});if(this._mfMedia&&this._mfMedia.removeEventListener)this._mfMedia.removeEventListener('change',this._mfReduced);const c=this.clock();if(c.raf!==null)global.cancelAnimationFrame(c.raf);c.raf=null;document.removeEventListener('visibilitychange',this.visibility);global.removeEventListener('resize',this.fitMap);if(global.speechSynthesis)global.speechSynthesis.cancel();}
 }));}
 global.MOMENTUM_FACTORY={hasConveyor,buyConveyor,walks,saleStock,automaticOutlet,stationStatus,speedPlan,applySpeed,guidedBuild,specialOrders:SPECIAL_ORDERS,canSpecial,startSpecial,cancelSpecial,specialStep,buildCosts:BUILD_COSTS,outletCosts:OUTLET_COSTS,preparePlay,boost,badges:BADGES,setSkin,guidance,types:TYPES,prices:PRICES,cash:CASH,contracts:CONTRACTS,order:ORDER,fresh,reward,buy,upgrade,hire,assign,relocate,manual,step,nextOrder,productionGrade,duration,assigned,total,themeKit,nextBuild,availableStock,prepareMarket,openOutlet,keepTrading};
 global.createMomentumFactoryComponent=createMomentumFactoryComponent;
})(typeof window!=='undefined'?window:globalThis);
