const {chromium}=require('playwright'),assert=require('assert');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(()=>{delete Navigator.prototype.serviceWorker;});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.goto('http://127.0.0.1:8767/');await page.waitForFunction(()=>typeof BaseGameComponent!=='undefined');
 await page.evaluate(()=>{const id='grp-ch51-6',a=getItemById(apps,id);setTheme('base');generateFromList(a.listName,a.questionIndex,a.resultIndex,id,getSetItems(a));setLocalStorage(id+'_new_items',[]);location.hash='/play/hexkeep/'+id;});assert.strictEqual(await page.locator('.hk-debug').count(),0);await page.locator('.hk-game').evaluate(e=>{const g=e.__vue__;if(g.battle.supplies!==0)throw Error('Expected zero starting funds');if(typeof g.toggleDebug!=='undefined')throw Error('Debug mode shipped');g.battle.supplies=100;g.phase='planning';});assert.strictEqual(await page.locator('.hk-build-panel,.hk-plot-picker').count(),0);assert(await page.locator('.hk-site').evaluateAll(es=>es.every(e=>!/[0-9]/.test(e.textContent))));
 await page.locator('.hk-site').nth(2).click();assert.strictEqual(await page.locator('.hk-blueprints button').count(),4);const desktopMenu=await page.locator('.hk-build-menu').boundingBox();assert(desktopMenu.y+desktopMenu.height<=1000);await page.screenshot({path:'artifacts/hexkeep/context-purchase.png',fullPage:true});await page.locator('.hk-blueprints button').nth(3).click();assert.strictEqual(await page.locator('.hk-build-menu').count(),0);assert.strictEqual(await page.locator('.hk-game').evaluate(e=>e.__vue__.battle.supplies),80);
 await page.locator('.hk-site').nth(2).click();assert.strictEqual(await page.locator('.hk-blueprints button').count(),0);await page.locator('.hk-upgrade').click();assert.strictEqual(await page.locator('.hk-game').evaluate(e=>e.__vue__.battle.supplies),56);
 await page.locator('.hk-game').evaluate(el=>{const g=el.__vue__;g.battle.turn=5;g.battle.spawned=HEXKEEP.targetCount(g.battle);g.battle.enemies=[{id:100,step:8,hp:20,maxHp:20},{id:101,step:9,hp:20,maxHp:20}];g.startRaid();});await page.clock.runFor(1100);assert.strictEqual(await page.locator('.hk-projectile').count(),1);const hp=()=>page.locator('.hk-game').evaluate(e=>e.__vue__.battle.enemies.map(v=>v.hp));assert.deepStrictEqual(await hp(),[20,20]);const start=await page.locator('.hk-projectile').evaluate(e=>e.style.transform);await page.clock.runFor(400);assert.notStrictEqual(await page.locator('.hk-projectile').evaluate(e=>e.style.transform),start);assert.deepStrictEqual(await hp(),[20,20]);await page.screenshot({path:'artifacts/hexkeep/catapult-flight.png',fullPage:true});
 await page.locator('.hk-study').click();const paused=await page.locator('.hk-projectile').evaluate(e=>e.style.transform);await page.clock.runFor(2000);assert.deepStrictEqual(await hp(),[20,20]);assert.strictEqual(await page.locator('.hk-projectile').evaluate(e=>e.style.transform),paused);await page.locator('.hk-return').click();await page.clock.runFor(500);assert.deepStrictEqual(await hp(),[17,17]);await page.clock.runFor(100);assert.deepStrictEqual(await hp(),[17,17]);
 await page.locator('.hk-study').click();await page.setViewportSize({width:390,height:844});await page.locator('.hk-return').click();await page.locator('.hk-site').nth(2).click();await page.screenshot({path:'artifacts/hexkeep/context-upgrade-mobile.png',fullPage:true});const rect=await page.locator('.hk-build-menu').boundingBox();assert(rect.x>=0&&rect.x+rect.width<=390&&rect.y>=0);assert.deepStrictEqual(errors,[]);console.log('PASS contextual purchase/upgrade, no numbered sites, real projectile, impact-only damage, midflight question pause, mobile menu');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
