const {chromium}=require('playwright'),assert=require('assert');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(()=>{delete Navigator.prototype.serviceWorker;});const page=await context.newPage();await page.clock.install();await page.goto('http://127.0.0.1:8767/');await page.waitForFunction(()=>typeof BaseGameComponent!=='undefined');
 await page.evaluate(()=>{const id='grp-ch51-6',a=getItemById(apps,id);setTheme('base');generateFromList(a.listName,a.questionIndex,a.resultIndex,id,getSetItems(a));setLocalStorage(id+'_new_items',[]);location.hash='/play/hexkeep/'+id;});assert.strictEqual(await page.locator('.hk-debug').count(),0);await page.locator('.hk-game').evaluate(e=>{const g=e.__vue__;if(g.battle.supplies!==0)throw Error('Expected zero starting funds');if(g.debugAvailable||g.debugMode)throw Error('Debug mode shipped');g.battle.supplies=100;g.phase='planning';});await page.locator('.hk-site').first().click();await page.locator('.hk-blueprints button').first().click();assert.strictEqual(await page.locator('.hk-soldier').count(),3);
 await page.locator('.hk-game').evaluate(el=>{const g=el.__vue__;g.battle.spawned=HEXKEEP.targetCount(g.battle);g.battle.enemies=Array.from({length:4},(_,i)=>({id:100+i,step:10,hp:12,maxHp:12}));g.startRaid();});await page.clock.runFor(1100);
 assert.strictEqual(await page.locator('.hk-guard-fighter').count(),3);assert.strictEqual(await page.locator('.hk-enemy-fighter').count(),3);assert.strictEqual(await page.locator('.hk-health-enemy').count(),4);assert.strictEqual(await page.locator('.hk-health-guard').count(),3);
 const gait=await page.locator('.hk-guard-fighter').first().evaluate(e=>e.style.backgroundPosition);await page.clock.runFor(400);assert.notStrictEqual(await page.locator('.hk-guard-fighter').first().evaluate(e=>e.style.backgroundPosition),gait);
 await page.clock.runFor(1160);assert.strictEqual(await page.locator('.hk-health-guard').first().getAttribute('aria-valuenow'),'4');assert.strictEqual(await page.locator('.hk-health-enemy').first().getAttribute('aria-valuenow'),'11');assert(await page.locator('.hk-game').evaluate(e=>e.__vue__.battle.enemies[3].step===12));await page.clock.runFor(400);await page.screenshot({path:'artifacts/hexkeep/melee-health-desktop.png',fullPage:true});
 await page.locator('.hk-study').click();const saved=await page.locator('.hk-game').evaluate(e=>JSON.stringify(e.__vue__.battle));const paused=await page.locator('.hk-guard-fighter').first().evaluate(e=>e.style.backgroundPosition);await page.clock.runFor(4000);assert.strictEqual(await page.locator('.hk-game').evaluate(e=>JSON.stringify(e.__vue__.battle)),saved);assert.strictEqual(await page.locator('.hk-guard-fighter').first().evaluate(e=>e.style.backgroundPosition),paused);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/hexkeep/melee-health-mobile.png',fullPage:true});assert(await page.locator('.hk-game').evaluate(e=>e.scrollWidth<=innerWidth));console.log('PASS 3 soldiers, one-to-one duels, bypass, two-sided health bars, attack animation, gradual damage, pause and mobile layout');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
