const {chromium}=require('playwright'),assert=require('assert');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});await context.addInitScript(()=>{delete Navigator.prototype.serviceWorker;});const page=await context.newPage();await page.goto('http://127.0.0.1:8767');await page.waitForFunction(()=>typeof BaseGameComponent!=='undefined');await page.evaluate(()=>{const id='6_0',a=getItemById(apps,id);generateFromList(a.listName,a.questionIndex,a.resultIndex,id,getSetItems(a));setLocalStorage(id+'_new_items',[]);location.hash='/play/hexkeep/'+id;});await page.waitForSelector('.hk-opening');await page.locator('.hk-opening button').tap();await page.locator('.hk-study').tap();const first=await page.locator('.hk-game').evaluate(e=>e.__vue__.options.indexOf(e.__vue__.question.result));await page.locator('.hk-answers button').nth(first).tap();await page.locator('.hk-game').evaluate(e=>{const g=e.__vue__;for(let i=1;i<26;i++){g.continueGame();g.answer(g.options.indexOf(g.question.result));}g.returnToVillage();});
 await page.locator('.hk-site').nth(4).tap();await page.locator('.hk-blueprints button').nth(1).tap();assert(await page.locator('.hk-game').evaluate(e=>e.__vue__.battle.buildings[4].type==='archer'));
 await page.locator('.hk-site').nth(0).tap();await page.locator('.hk-blueprints button').nth(0).tap();assert(await page.locator('.hk-game').evaluate(e=>e.__vue__.battle.buildings[0].type==='guard'));
 assert(!await page.locator('.hk-plot-picker').count());assert(await page.locator('.hk-site').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().width>=43&&e.getBoundingClientRect().height>=43)));
 await page.locator('.hk-launch').tap();await page.waitForFunction(()=>document.querySelector('.hk-game').__vue__.battle.turn===1);assert(await page.locator('.hk-game').evaluate(e=>e.__vue__.battle.earned===26&&e.__vue__.battle.supplies===0));
 await page.screenshot({path:'artifacts/hexkeep/mobile-play.png',fullPage:true});console.log('4 mobile touch checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
