const {chromium}=require('playwright'),assert=require('assert');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(()=>{delete Navigator.prototype.serviceWorker;});const page=await context.newPage();
 await page.goto('http://127.0.0.1:8767/');await page.waitForFunction(()=>typeof BaseGameComponent!=='undefined');
 await page.evaluate(()=>{const id='grp-ch51-6',a=getItemById(apps,id);setTheme('base');setLocalStorage(getActivityMode()+'_'+id+'_Weights',getDataList(a.listName).map(()=>15));setLocalStorage(id+'_CurrentLevelProgress',{progress:0,total:675});setLocalStorage(id+'_new_items',[]);location.hash='/play/hexkeep/'+id;});await page.locator('.hk-opening button').click();
 await page.locator('.hk-game').evaluate(e=>e.__vue__.startRaid());await page.waitForFunction(()=>document.querySelector('.hk-game').__vue__.battle.turn===2);
 const matrix=()=>page.locator('.hk-enemy').first().evaluate(e=>getComputedStyle(e).transform);
 await page.waitForTimeout(180);const gait=await page.locator('.hk-walker').first().evaluate(e=>e.style.backgroundPosition);const a=await matrix();await page.waitForTimeout(220);const b=await matrix();assert.notStrictEqual(a,b,'enemy interpolates between ticks');assert.notStrictEqual(await page.locator('.hk-walker').first().evaluate(e=>e.style.backgroundPosition),gait,'skeletal gait advances');
 await page.locator('.hk-study').click();const paused=await matrix(),pausedGait=await page.locator('.hk-walker').first().evaluate(e=>e.style.backgroundPosition);await page.waitForTimeout(500);assert.strictEqual(await matrix(),paused,'question freezes enemy at exact visual position');assert.strictEqual(await page.locator('.hk-walker').first().evaluate(e=>e.style.backgroundPosition),pausedGait,'gait pauses with position');
 const before=await page.locator('.hk-game').evaluate(e=>e.__vue__.battle.turn);await page.locator('.hk-game').evaluate(e=>{const g=e.__vue__;g.answer(g.options.indexOf(g.question.result));});await page.waitForTimeout(850);assert(await page.locator('.hk-game').evaluate(e=>e.__vue__.phase==='ready'));assert.strictEqual(await page.locator('.hk-game').evaluate(e=>e.__vue__.battle.turn),before,'auto-next never unpauses combat');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/hexkeep/hebrew-learning-mobile.png',fullPage:true});await page.locator('.hk-return').click();
 const deltas=await page.evaluate(()=>new Promise(resolve=>{const samples=[];let last=null,start=performance.now();function sample(){const el=document.querySelector('.hk-enemy');if(!el){resolve(samples);return;}const m=new DOMMatrix(getComputedStyle(el).transform),now=performance.now();if(last)samples.push({distance:Math.hypot(m.m41-last.x,m.m42-last.y),dt:now-last.t});last={x:m.m41,y:m.m42,t:now};if(now-start>2500)resolve(samples);else requestAnimationFrame(sample);}requestAnimationFrame(sample);}));assert(deltas.length>30&&deltas.every(d=>d.distance<.3*d.dt+1),'mobile motion has no boundary or resume position jump');await page.screenshot({path:'artifacts/hexkeep/walking-mobile.png',fullPage:true});
 await page.locator('.hk-game').evaluate(e=>{const g=e.__vue__;g.invalidate();g.phase='planning';g.battle=HEXKEEP.freshBattle();g.battle.supplies=500;['guard','archer','mage','catapult','archer','mage'].forEach((type,i)=>{g.selectSite(i);g.selectedType=type;g.buildSelected();g.upgradeSelected();g.upgradeSelected();});});
 await page.setViewportSize({width:1440,height:1000});await page.waitForFunction(()=>[...document.querySelectorAll('.hk-game img')].every(i=>i.complete&&i.naturalWidth));await page.screenshot({path:'artifacts/hexkeep/four-combat-towers.png',fullPage:true});
 assert(await page.locator('.hk-game').evaluate(e=>e.__vue__.battle.buildings.every(b=>b&&b.level===3)));console.log('8 walk-cycle, continuous-motion, pause, automatic-question and tower-art checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
