const {chromium}=require('playwright'),assert=require('assert');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{delete Navigator.prototype.serviceWorker;});await p.clock.install();await p.clock.pauseAt(new Date(Date.now()+1000));await p.goto('http://127.0.0.1:8873/');await p.waitForFunction(()=>window.MOMENTUM_FACTORY);
 await p.evaluate(()=>{const id='grp-ch51-7',a=getItemById(apps,id);setLocalStorage(getActivityMode()+'_'+id+'_Weights',getDataList(a.listName).map(()=>50));setLocalStorage(id+'_CurrentLevelProgress',{progress:0,total:9999});setLocalStorage(id+'_new_items',[]);location.hash='/play/momentum_factory/'+id;});await p.locator('.mf-start').click();
 for(let n=0;n<70;n++){const g=await p.locator('.mf-game').evaluate(e=>({visits:e.__vue__.market.visits,remaining:e.__vue__.guideRemaining,action:e.__vue__.guide.action,phase:e.__vue__.phase}));if(g.visits)break;if(g.remaining){await p.locator('.mf-guide-action').click();for(let i=0;i<g.remaining;i++){await p.locator('.mf-game').evaluate(e=>{const g=e.__vue__;g.answer(g.options.indexOf(g.question.result));});await p.clock.runFor(720);}await p.locator('.mf-return').click();}else if(g.action==='wait'&&g.phase==='running')await p.clock.runFor(1000);else await p.locator('.mf-guide-action').click();}
 await p.locator('.mf-shop-sign').click();await p.locator('.mf-special-entry').click();assert(await p.locator('.mf-special-send').nth(1).isDisabled(),'missing press explained before parts request');await p.screenshot({path:'artifacts/momentum-factory/robo-special-choice.png'});
 for(const [w,h]of [[844,390],[320,568],[1365,900]]){await p.setViewportSize({width:w,height:h});assert(await p.locator('.mf-special-dialog').evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=10&&r.y>=10&&r.right<=innerWidth-10&&r.bottom<=innerHeight-10;}));}
 await p.setViewportSize({width:390,height:844});await p.locator('.mf-special-send').first().click();assert(await p.locator('.mf-game').evaluate(e=>!!e.__vue__.play.special));await p.locator('.mf-view-toggle').click();assert.equal(await p.locator('.mf-view-toggle').getAttribute('aria-pressed'),'true');assert(await p.locator('.mf-special-visitor').evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth;}),'recipient visible in whole-factory camera');await p.clock.runFor(2500);await p.locator('.mf-study').click();const frozen=await p.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory));await p.clock.runFor(2000);assert.equal(await p.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory)),frozen);await p.locator('.mf-return').click();
 let elapsed=0;while(await p.locator('.mf-game').evaluate(e=>e.__vue__.play.special.phase!=='carry')){await p.clock.runFor(100);if((elapsed+=100)>40000)throw Error('collection stalled');}
 await p.screenshot({path:'artifacts/momentum-factory/robo-special-delivery.png'});await p.locator('.mf-run').click();const snap=await p.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory));await p.reload();await p.locator('.mf-run').waitFor();assert.equal(await p.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory)),snap);await p.locator('.mf-run').click();await p.clock.runFor(3000);
 assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.play.deliveries===1&&!e.__vue__.play.special&&e.__vue__.factory.earned===6&&e.__vue__.factory.money>=14));await p.locator('.mf-collection-open').click();assert(!await p.locator('.mf-badge-grid button').filter({hasText:'חבר של השכונה'}).evaluate(e=>e.classList.contains('is-locked')));await p.screenshot({path:'artifacts/momentum-factory/robo-special-prize.png'});assert.deepEqual(errors,[]);
 console.log('PASS six-answer start to optional special delivery, competing shop stock gathered automatically, physical courier, question pause, carry-phase reload, once-only payment, earned badge and bounded choice UI');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
