const fs=require('fs'),vm=require('vm'),assert=require('assert');const c={};vm.createContext(c);vm.runInContext(fs.readFileSync('games/momentum-factory.js','utf8'),c);const F=c.MOMENTUM_FACTORY;
function fresh(){const s=F.fresh();F.preparePlay(s);F.prepareMarket(s);s.started=true;s.market.visits=1;s.buildings[1]={type:'supply',level:1,worker:false,pending:0,manual:false};s.stock.raw[0]=3;return s;}
function tick(s,n){for(let i=0;i<n;i+=100)F.step(s,Math.min(100,n-i));}
const s=fresh();assert(F.startSpecial(s,'raw'));assert(!F.startSpecial(s,'raw'),'no double request');assert.equal(s.stock.raw[0],3,'not consumed before physical pickup');assert.equal(F.availableStock(s,'raw',1),0,'reserved from other workers');assert.equal(s.money,0);
tick(s,1700);assert.equal(s.stock.raw[0],3);tick(s,100);assert.equal(s.stock.raw[0],0);assert.equal(s.play.special.phase,'carry');assert.equal(s.money,0);
const saved=JSON.parse(JSON.stringify(s));tick(s,2800);tick(saved,2800);assert.equal(JSON.stringify(s),JSON.stringify(saved));assert.equal(s.money,12);assert.equal(s.play.deliveries,1);assert.equal(s.points,0);assert.equal(s.play.special,null);tick(s,5000);assert.equal(s.money,12,'single physical payment');assert(F.badges.find(b=>b.id==='helper').test(s));
for(const time of [0,1800,3700]){const r=fresh();assert(F.startSpecial(r,'raw'));tick(r,time);const before=r.money;assert(F.relocate(r,1,6));assert.equal(r.stock.raw[0],3,'relocation restores picked load once');assert.equal(r.play.special,null);tick(r,6000);assert.equal(r.money,before);}
const paused=fresh();F.startSpecial(paused,'raw');tick(paused,2200);paused.started=false;const snapshot=JSON.stringify(paused);tick(paused,10000);assert.equal(JSON.stringify(paused),snapshot);
const contested=fresh();contested.stock.raw[0]=4;contested.jobs.push({site:2,source:1,type:'press',input:'raw',grade:1,amount:2,picked:false,phase:'out',elapsed:0,duration:2000});assert(F.startSpecial(contested,'raw'));assert.equal(contested.play.special.phase,'gather');tick(contested,500);assert.equal(contested.stock.raw[0],4,'does not steal earlier reserved stock');assert.equal(contested.play.special.phase,'gather');contested.jobs=[];tick(contested,100);assert.equal(contested.play.special.phase,'out','collects only after stock is free');
const growing=fresh();growing.stock.raw[0]=0;growing.buildings[1].worker=true;growing.market.outlets.raw=true;assert(F.startSpecial(growing,'raw'));tick(growing,40000);assert.equal(growing.play.deliveries,1,'can finish a request even while ordinary shop sells the same material');assert(growing.stock.raw.every(n=>n>=0));
const older=F.fresh();older.play={energy:2,boost:1000,boosts:1,skin:'gold',seen:[],sound:false};F.preparePlay(older);assert.equal(older.play.energy,2);assert.equal(older.play.special,null);assert.equal(older.play.deliveries,0);
const cancelled=fresh();F.startSpecial(cancelled,'raw');tick(cancelled,2000);assert.equal(cancelled.stock.raw[0],0);assert(F.cancelSpecial(cancelled));assert(!F.cancelSpecial(cancelled));assert.equal(cancelled.stock.raw[0],3);tick(cancelled,5000);assert.equal(cancelled.money,0);assert.equal(cancelled.play.deliveries,0);
console.log('PASS optional delivery reservations, actual pickup and handoff, one payment, concurrent stock safety, pause, in-transit reload, relocation recovery, old play-state migration, no knowledge currency creation');
