const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs');
fs.mkdirSync('artifacts/momentum-factory',{recursive:true});let checks=0;
function check(v,label){assert.ok(v,label);checks++;console.log('PASS',label);}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:1365,height:900}});await context.addInitScript(()=>{delete Navigator.prototype.serviceWorker;});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.clock.pauseAt(new Date(Date.now()+1000));
 await page.goto('http://127.0.0.1:8873/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>typeof BaseGameComponent!=='undefined');
 const game=()=>page.locator('.mf-game');const state=()=>game().evaluate(e=>JSON.parse(JSON.stringify(e.__vue__.factory)));
 await page.evaluate(()=>{const id='grp-ch51-7',a=getItemById(apps,id);setLocalStorage(getActivityMode()+'_'+id+'_Weights',getDataList(a.listName).map(()=>15));setLocalStorage(id+'_CurrentLevelProgress',{progress:0,total:getDataList(a.listName).length*15});setLocalStorage(id+'_new_items',[0,1]);location.hash='/play/momentum_factory/'+id;});
 await page.locator('.mf-news-next').waitFor();check(page.url().includes('/play/momentum_factory/'),'new words use world overlay without navigation');const frozen=JSON.stringify(await state());await page.clock.runFor(3000);check(JSON.stringify(await state())===frozen,'new-word presentation freezes world');await page.locator('.mf-news-next').click();check(await page.evaluate(()=>getLocalStorage('grp-ch51-7_new_items',[]).length)===2,'new words acknowledged only after final word');await page.screenshot({path:'artifacts/momentum-factory/new-words.png'});await page.locator('.mf-news-next').click();await page.locator('.mf-answers button').first().waitFor();check(await page.evaluate(()=>getLocalStorage('grp-ch51-7_new_items',[]).length)===0,'new-word completion clears engine acknowledgment');
 const first=await game().evaluate(e=>{const g=e.__vue__;return {question:JSON.stringify(g.question),options:g.options.slice(),correct:g.options.indexOf(g.question.result),index:g.questionIndex};});await page.locator('.mf-answers button').nth((first.correct+1)%4).click();await game().evaluate(e=>e.__vue__.answer(0));check(await game().evaluate(e=>e.__vue__.phase)==='retry','rapid input locked after incorrect attempt');await page.locator('.mf-retry').click();check(await game().evaluate(e=>JSON.stringify(e.__vue__.question))===first.question,'retry retains exact question');assert.deepStrictEqual(await game().evaluate(e=>e.__vue__.options),first.options);
 await page.locator('.mf-answers button').nth(first.correct).click();await game().evaluate(e=>e.__vue__.answer(e.__vue__.options.indexOf(e.__vue__.question.result)));check((await state()).earned===1,'double correct input rewards only once');await page.clock.runFor(500);check(await game().evaluate(e=>e.__vue__.phase)==='resolved','success remains readable');await page.clock.runFor(250);check(await game().evaluate(e=>e.__vue__.phase)==='ready','correct answer automatically advances');
 // Actual learning transactions fund every purchase: only weights, never currency, were seeded.
 for(let i=1;i<238;i++){await game().evaluate(e=>{const g=e.__vue__;g.answer(g.options.indexOf(g.question.result));});await page.clock.runFor(720);}
 check((await state()).earned===238&&(await state()).points===238,'238 accepted engine answers fund the complete campaign');check(await page.evaluate(()=>getScore('grp-ch51-0')===getScore('grp-ch51-7')),'score shares the existing chapter knowledge group');await page.locator('.mf-return').click();

 async function open(site){await page.locator('[data-site="'+site+'"]').click();}
 for(const [i,name]of ['מחסן העצים','מכונת החלקים','בונה הרובוטים','אורזת ההפתעות','עמדת המשלוחים'].entries()){await open(i+1);await page.locator('.mf-blueprints button').filter({hasText:name}).click();}
 check((await state()).buildings.filter(Boolean).length===5,'five real machines bought through contextual floor menus');
 await page.locator('.mf-team').click();for(let i=0;i<4;i++)await page.locator('.mf-hire').click();await page.locator('.mf-context header button').click();
 await page.locator('.mf-run').click();await page.clock.runFor(3200);
 for(let site=1;site<=5;site++){await open(site);await page.locator('.mf-assign').click();await page.locator('.mf-context header button').click();}
 check((await state()).employees===5,'learning points recruit a full factory team');await page.clock.runFor(600);
 while((await state()).jobs.find(j=>j.site===1)?.phase!=='fetch')await page.clock.runFor(100);
 const cargo=await page.locator('[data-job="1"]').getAttribute('style');await page.clock.runFor(200);check(await page.locator('[data-job="1"] .mf-gait').count()===1&&cargo!==await page.locator('[data-job="1"]').getAttribute('style'),'initial worker carries materials before conveyor upgrades');
 while((await state()).jobs.find(j=>j.site===1)?.phase!=='work')await page.clock.runFor(100);const frame=await page.locator('[data-operator="1"] .mf-gait').getAttribute('style');await page.clock.runFor(200);check(frame!==await page.locator('[data-operator="1"] .mf-gait').getAttribute('style'),'stationary operator animates the real work phase');

 await page.locator('.mf-study').click();const paused=JSON.stringify(await state()),position=await page.locator('[data-job="1"]').getAttribute('style');await page.clock.runFor(2700);check(JSON.stringify(await state())===paused&&await page.locator('[data-job="1"]').getAttribute('style')===position,'question pauses production, deliveries and gait');await page.locator('.mf-return').click();await page.clock.runFor(600);check((await state()).time>JSON.parse(paused).time,'question return resumes the same factory clock');
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});const hidden=JSON.stringify(await state());await page.clock.runFor(5000);check(JSON.stringify(await state())===hidden,'backgrounding freezes remaining timings');await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});
 await page.locator('.mf-run').click();const save=await state();await page.reload({waitUntil:'domcontentloaded'});await page.locator('.mf-run').waitFor();assert.deepStrictEqual(await state(),save);check(await game().evaluate(e=>e.__vue__.phase)==='planning','reload restores full pending jobs and waits for explicit resume');await page.locator('.mf-run').click();
 for(let order=0;order<3;order++){
  let elapsed=0;while(!(await state()).outcome){await page.clock.runFor(1000);elapsed+=1000;if(elapsed===5000)await page.screenshot({path:'artifacts/momentum-factory/line-level-'+(order+1)+'.png'});if(elapsed>240000)throw Error('Order did not complete');}
  check((await state()).order===order+1,'visible production and delivery fulfil order '+(order+1));const ending=JSON.stringify(await state());await page.clock.runFor(2500);check(JSON.stringify(await state())===ending,'order completion pauses all machinery');
  if(order<2){await page.locator('.mf-next-order').click();for(let site=1;site<=5;site++){await open(site);await page.locator('.mf-upgrade').click();}check((await state()).buildings.filter(Boolean).every(b=>b.level===order+2),'learning and sales currency buy all machine upgrades');await page.locator('.mf-run').click();await page.clock.runFor(3200);}
 }
 check((await state()).outcome==='victory'&&(await state()).earned===238&&(await state()).points===0,'complete real winning campaign with 238 accepted answers');check((await state()).sold===42,'42 products sold only on delivery');await page.screenshot({path:'artifacts/momentum-factory/victory.png'});
 await page.locator('.mf-next-order').click();await page.clock.runFor(30000);check((await state()).endless&&(await state()).sold>42,'victory continues as an autonomous profitable factory');await page.locator('.mf-exit').click();await page.clock.runFor(1000);check(!await game().count(),'navigation tears down active factory');check(errors.length===0,'no runtime errors: '+errors.join('; '));console.log(checks+' Momentum Factory browser checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
