const {chromium}=require('playwright'),assert=require('assert');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{delete Navigator.prototype.serviceWorker;});await p.clock.install();await p.clock.pauseAt(new Date(Date.now()+1000));await p.goto('http://127.0.0.1:8873/');await p.waitForFunction(()=>window.MOMENTUM_FACTORY);await p.evaluate(()=>{const id='grp-ch51-7',a=getItemById(apps,id);setLocalStorage(getActivityMode()+'_'+id+'_Weights',getDataList(a.listName).map(()=>50));setLocalStorage(id+'_CurrentLevelProgress',{progress:0,total:9999});setLocalStorage(id+'_new_items',[]);location.hash='/play/momentum_factory/'+id;});await p.screenshot({path:'artifacts/momentum-factory/factory-simple-start.png'});await p.locator('.mf-start').click();
 async function answers(n){for(let i=0;i<n;i++){await p.locator('.mf-game').evaluate(e=>{const g=e.__vue__;g.answer(g.options.indexOf(g.question.result));});await p.clock.runFor(720);}}
 await p.locator('.mf-guide-action').click();await answers(3);await p.locator('.mf-return').click();await p.locator('.mf-guide-action').click();assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.phase==='running'&&e.__vue__.factory.buildings[1].worker));await p.clock.runFor(3200);
 await p.locator('.mf-guide-action').click();await answers(3);await p.locator('.mf-return').click();await p.locator('.mf-guide-action').click();await p.clock.runFor(26000);assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.market.visits>0));
 await p.locator('.mf-guide-action').click();await answers(10);await p.locator('.mf-return').click();await p.locator('.mf-guide-action').click();await p.clock.runFor(3200);await p.locator('.mf-speed-open').click();assert(await p.locator('.mf-speed-dialog').innerText().then(t=>t.includes('עובד קבוע')));await p.locator('.mf-speed-action').click();assert(await p.locator('.mf-learning-goal').innerText().then(t=>t.includes('עובד קבוע')));await answers(5);await p.locator('.mf-speed-action').waitFor();assert.equal(await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.earned),21);await p.locator('.mf-speed-action').click();assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.buildings[2].worker));await p.clock.runFor(14000);
 assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.stock.parts[0]>0),'real production after improvement');assert.equal(await p.locator('.mf-flow-stations button').count(),2);
 // Three further real machines complete the visual concurrency fixture; learning remains genuine above.
 await p.locator('.mf-game').evaluate(e=>{const g=e.__vue__,F=MOMENTUM_FACTORY;for(let i=0;i<45;i++)F.reward(g.factory);for(let i=2;i<5;i++){F.guidedBuild(g.factory,i+1,F.order[i]);g.factory.buildings[i+1].pending=0;F.hire(g.factory);F.assign(g.factory,i+1);}g.save();});await p.clock.runFor(16000);
 for(const [w,h]of [[1365,900],[390,844],[320,568],[844,390],[667,320]]){await p.setViewportSize({width:w,height:h});await p.screenshot({path:'artifacts/momentum-factory/factory-flow-'+w+'.png'});assert(await p.locator('.mf-flow-stations button').evaluateAll(es=>es.every(e=>{const r=e.getBoundingClientRect();return r.width>=44&&r.height>=44&&r.x>=0&&r.right<=innerWidth;})),'flow controls fit '+w);await p.locator('.mf-speed-open').click();assert(await p.locator('.mf-speed-dialog').evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=10&&r.y>=10&&r.right<=innerWidth-10&&r.bottom<=innerHeight-10;}),'speed panel bounded '+w);assert(!await p.locator('.mf-game').innerText().then(t=>t.includes('{{')),'all user-visible bindings compiled');await p.screenshot({path:'artifacts/momentum-factory/factory-speed-'+w+'.png'});await p.locator('.mf-speed-dialog button[aria-label="סגירה"]').click();}
 await p.locator('.mf-game').evaluate(e=>{for(const b of e.__vue__.factory.buildings)if(b&&b.type!=='supply')b.conveyor=true;});await p.setViewportSize({width:390,height:844});for(let i=0;i<60&&await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.money<10);i++)await p.clock.runFor(1000);await p.locator('.mf-speed-open').click();await p.locator('.mf-speed-action').click();await answers(15);await p.locator('.mf-speed-action').waitFor();assert.equal(await p.locator('.mf-speed-action').innerText(),'משדרגים את המכונה');await p.locator('.mf-speed-action').click();await p.locator('.mf-game').evaluate(e=>e.__vue__.improveSpeed());assert.equal(await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.buildings.filter(b=>b&&b.level===2).length),1,'repeat UI callback cannot upgrade another machine');await p.clock.runFor(3200);assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.buildings[1].level===2&&!e.__vue__.factory.buildings[1].pending&&e.__vue__.notice.kind==='improved'));await p.screenshot({path:'artifacts/momentum-factory/factory-upgrade-success.png'});
 await p.locator('.mf-run').click();const saved=await p.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory));await p.reload();await p.locator('.mf-run').waitFor();assert.equal(await p.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory)),saved);assert.deepEqual(errors,[]);console.log('PASS real 3-answer automatic start, 6-answer sale, 21-answer two-worker parallel factory, focused speed learning and automatic return, five flow/panel sizes, real output and save restoration');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
