const fs=require('fs'),vm=require('vm'),assert=require('assert');const c={};vm.createContext(c);vm.runInContext(fs.readFileSync('games/momentum-factory.js','utf8'),c);const F=c.MOMENTUM_FACTORY,tick=(s,n)=>{for(let t=0;t<n;t+=100)F.step(s,100);};
// Reproduce the supplied screenshot: three staffed stations, 17 completed products,
// waiting customers, no packing/shipping and no side request.
const s=F.fresh();F.prepareMarket(s);F.preparePlay(s);s.started=true;s.employees=3;for(let i=0;i<3;i++)s.buildings[i+1]={type:F.order[i],level:1,worker:true,pending:0,manual:false};s.stock.products[0]=17;s.market.visits=1;
tick(s,100);assert(s.market.porter&&s.market.porter.kind==='products');assert.equal(s.stock.products[0],17,'goods stay on machine until loading');assert.equal(s.money,0);tick(s,1800);assert(s.market.porter.picked);assert.equal(s.stock.products[0],15);assert.equal(s.money,0,'cargo on belt has not been sold');const restored=JSON.parse(JSON.stringify(s));tick(s,20000);tick(restored,20000);assert.equal(JSON.stringify(s),JSON.stringify(restored),'in-flight belt load restores once');assert(s.market.visits>2&&s.money>0);assert.equal(s.play.special,null);assert.equal(s.delivered,0,'unboxed sales do not replace campaign delivery');assert.equal(s.earned,0);
s.buildings[4]={type:'packing',level:1,worker:true,pending:0,manual:false};s.employees=4;tick(s,60000);assert(F.total(s,'boxes')>0,'shop leaves materials for downstream packaging');assert(F.total(s,'products')>=0);assert(s.market.visits>4,'shop and manufacturing continue concurrently');
assert.equal(F.duration({level:1,worker:true},'fetch'),F.duration({level:1,worker:false},'fetch'),'staffing does not change conveyor speed');assert(F.duration({level:1,worker:true},'work')<F.duration({level:1,worker:false},'work'),'staffing improves operation');
s.started=false;const frozen=JSON.stringify(s);tick(s,2000);assert.equal(JSON.stringify(s),frozen);console.log('PASS screenshot reproduction sells 17-product backlog automatically without requests, physical conveyor loading before removal, checkout before payment, preserved downstream stock, once-only reload, stationary-worker timing and pause');

const b=F.fresh();b.started=true;b.employees=2;b.money=20;for(let i=0;i<2;i++)b.buildings[i+1]={type:F.order[i],level:1,worker:true,pending:0};b.stock.raw[0]=10;
assert(!F.hasConveyor(b.buildings[2]));tick(b,1500);assert(F.walks(b.jobs.find(j=>j.site===2)));const before=b.stock.raw[0];assert(F.buyConveyor(b,2));assert.equal(b.money,10);assert.equal(b.stock.raw[0],before+1,'purchase returns carried input once');assert(!F.buyConveyor(b,2));assert.equal(b.money,10);assert(!F.buyConveyor(b,1),'forest gathering never gets a conveyor');tick(b,400);assert(!F.walks(b.jobs.find(j=>j.site===2)));assert(F.hasConveyor(b.buildings[2]));assert(F.duration(b.buildings[2],'fetch')+F.duration(b.buildings[2],'out')<1300,'paid transport is faster');const saved=JSON.parse(JSON.stringify(b));tick(b,12000);tick(saved,12000);assert.equal(JSON.stringify(b),JSON.stringify(saved));assert(F.walks({phase:'delivery',conveyor:true}),'customer deliveries always use people');console.log('PASS employee start, paid internal conveyor, no double charge, safe in-flight purchase, persisted conveyor, human deliveries');
