const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs');fs.mkdirSync('artifacts/momentum-factory',{recursive:true});let checks=0;function check(v,label){assert.ok(v,label);checks++;console.log('PASS',label);}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});await context.addInitScript(()=>{delete Navigator.prototype.serviceWorker;});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.goto('http://127.0.0.1:8873/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>typeof BaseGameComponent!=='undefined');
 for(const [id,list,q,r]of [['grp-ch51-7','5_1','english_name','hebrew'],['grp-ch51s-7','5_1','english_name','hebrew'],['grp-g611-13','6.1_1','english_name','hebrew'],['grp-g611h-13','6.1_1','hebrew','english']]){
  const actual=await page.evaluate(id=>{const a=getItemById(apps,id);setLocalStorage(getActivityMode()+'_'+id+'_Weights',getDataList(a.listName).map((_,i)=>i<getSetItems(a)?50:-1));setLocalStorage(id+'_CurrentLevelProgress',{progress:0,total:400});setLocalStorage(id+'_new_items',[]);location.hash='/play/momentum_factory/'+id;return [a.listName,a.questionIndex,a.resultIndex];},id);assert.deepStrictEqual(actual,[list,q,r]);await page.locator('.mf-start').waitFor();await page.locator('.mf-start').tap();await page.locator('.mf-study').tap();await page.locator('.mf-answers button').first().waitFor();check(await page.locator('.mf-game').evaluate(e=>{const g=e.__vue__,row=getDataList(g.currentApp.listName)[g.questionIndex];return g.question.result===row[g.currentApp.resultIndex].value;}),'engine content and direction '+id);const correct=await page.locator('.mf-game').evaluate(e=>e.__vue__.options.indexOf(e.__vue__.question.result));await page.locator('.mf-answers button').nth(correct).tap();await page.clock.runFor(750);check(await page.locator('.mf-game').evaluate(e=>e.__vue__.factory.earned)===1,'touch answer on '+id);await page.screenshot({path:'artifacts/momentum-factory/direction-'+id+'.png'});
 }
 const themes=await page.evaluate(()=>Object.keys(themeOptions));
 for(const theme of themes){await page.locator('.mf-game').evaluate((e,key)=>{e.__vue__.theme=themeOptions[key];},theme);check(await page.locator('.mf-overlay').evaluate(el=>{const r=el.getBoundingClientRect();return r.x>=12&&r.y>=12&&r.right<=innerWidth-12&&r.bottom<=innerHeight-12;}),'bounded readable theme '+theme);await page.screenshot({path:'artifacts/momentum-factory/theme-'+theme+'.png'});}
 await page.locator('.mf-game').evaluate(e=>{e.__vue__.theme=themeOptions.base;});
 for(const size of [{width:390,height:844},{width:844,height:390},{width:320,height:568},{width:667,height:320},{width:1365,height:900}]){await page.setViewportSize(size);const box=await page.locator('.mf-overlay').boundingBox();check(box.x>=10&&box.y>=10&&box.x+box.width<=size.width-10&&box.y+box.height<=size.height-10,'question overlay fits '+size.width+'×'+size.height);check(await page.locator('.mf-answers button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44)),'comfortable answer targets '+size.width);await page.screenshot({path:'artifacts/momentum-factory/layout-'+size.width+'x'+size.height+'.png'});}
 await page.setViewportSize({width:390,height:844});await page.locator('.mf-return').tap();check(await page.locator('.mf-office').evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>150&&r.bottom<innerHeight-120;}),'initial portrait framing includes factory office');
 check(await page.locator('.mf-site').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().width>=44&&e.getBoundingClientRect().height>=44)),'all map targets at least 44px');
 // Isolated saved fixture for art/touch/assignment QA; never a runtime funding mode.
 await page.locator('.mf-game').evaluate(e=>{const g=e.__vue__;for(let n=0;n<50;n++)MOMENTUM_FACTORY.reward(g.factory);});await page.locator('[data-site="1"]').tap();await page.locator('.mf-blueprints button').filter({hasText:'מחסן העצים'}).tap();await page.locator('.mf-run').tap();await page.clock.runFor(3200);await page.screenshot({path:'artifacts/momentum-factory/mobile-factory.png'});
 await page.locator('[data-site="1"]').tap();check(await page.locator('.mf-context').evaluate(el=>{const r=el.getBoundingClientRect();return r.x>=10&&r.y>=10&&r.right<=innerWidth-10&&r.bottom<=innerHeight-10;}),'touch contextual building menu stays in viewport');await page.locator('.mf-context header button').tap();await page.locator('.mf-study').tap();await page.locator('.mf-return').focus();await page.keyboard.press('Tab');check(await page.locator('.mf-overlay').evaluate(el=>el.contains(document.activeElement)),'keyboard tab stays in learning overlay');await page.keyboard.press('Escape');check(!await page.locator('.mf-overlay').count(),'Escape returns to factory');
 await page.emulateMedia({reducedMotion:'reduce'});await page.reload({waitUntil:'domcontentloaded'});await page.locator('.mf-game').waitFor();check(await page.locator('.mf-game').evaluate(e=>e.__vue__.reduced),'reduced motion respected on load');
 // Engine completion retains the reward and uses the existing chapter entry route.
 await page.evaluate(()=>{const id='grp-g611h-13',a=getItemById(apps,id);setLocalStorage(getActivityMode()+'_'+id+'_Weights',getDataList(a.listName).map((_,i)=>i===0?1:0));setLocalStorage(id+'_CurrentLevelProgress',{progress:0,total:1});setLocalStorage(id+'_new_items',[]);});await page.locator('.mf-study').tap();await page.locator('.mf-game').evaluate(e=>{const g=e.__vue__;g.answer(g.options.indexOf(g.question.result));});await page.clock.runFor(750);check(page.url().includes('/app/grp-g611h-13'),'learning-stage completion follows engine route');check(await page.evaluate(()=>getLocalStorage('grp-g611h-13_MomentumFactory_v1').factory.earned)===52,'stage-completing answer saved once before navigation');check(errors.length===0,'no layout/route errors: '+errors.join('; '));console.log(checks+' layout, theme and direction checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
