const fs=require('fs'),vm=require('vm'),assert=require('assert');
let component;const ctx={console,Vue:{extend:x=>x,component:(_,x)=>(component=x)}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('games/momentum-factory.js','utf8'),ctx);const F=ctx.MOMENTUM_FACTORY;
let checks=0;function check(v,label){assert.ok(v,label);checks++;console.log('PASS',label);}function advance(s,ms){for(let t=0;t<ms&&!s.outcome;t+=100)F.step(s,100);}function until(s,p,label,max=600000){for(let t=0;t<max&&!p();t+=100)F.step(s,100);check(p(),label);}
const s=F.fresh();check(s.points===0&&s.money===0&&s.employees===1&&!s.started,'one starting worker; no free funding or automatic start');
for(let i=0;i<238;i++)F.reward(s);for(let i=0;i<4;i++)check(F.hire(s),'hire employee '+(i+2));for(const [i,type]of F.order.entries())check(F.buy(s,i+1,type),'buy '+type);check(!F.buy(s,6,'supply'),'duplicate stations cannot substitute for useful upgrades');s.started=true;advance(s,3000);for(let i=1;i<=5;i++)check(F.assign(s,i),'assign worker '+i);
for(let order=0;order<3;order++){
 until(s,()=>s.outcome!==null,'complete real factory order '+(order+1));check(s.order===order+1,'shipping arrival completes correct grade order');if(order<2){check(s.outcome==='milestone','order ending pauses');const saved=JSON.stringify(s);F.step(s,2000);check(JSON.stringify(s)===saved,'ending freezes machine jobs and deliveries');F.nextOrder(s);for(let site=1;site<=5;site++)check(F.upgrade(s,site),'sales fund upgrade '+site+' to level '+(order+2));advance(s,3000);}
}
check(s.outcome==='victory'&&s.earned===238&&s.points===0&&s.spent===238,'complete practical winning strategy uses 238 correct answers');check(s.money>=360&&s.sold>=42,'completed deliveries produce sales money separately');
let min=Infinity,legal=0;for(let code=0;code<1024;code++){let x=code;const t=F.fresh();t.order=2;let cost=0;for(let i=0;i<5;i++){const level=x%4;x=Math.floor(x/4);if(level)t.buildings[i+1]={type:F.order[i],level,pending:0,worker:true};cost+=level?F.buildCosts[F.order[i]]+F.prices.slice(1,level).reduce((a,b)=>a+b,0):0;}if(F.productionGrade(t)===3){legal++;min=Math.min(min,cost);}}
check(legal===1&&min===218,'all 1,024 station configurations: robot-capable line costs at least 218 points');check(!('refund' in F)&&!('salvage' in F),'no stockpile/refund or sale-money conversion shortcut');
const m=F.fresh();for(let i=0;i<10;i++)F.reward(m);F.buy(m,1,'supply');m.started=true;advance(m,3000);advance(m,30000);check(F.total(m,'raw')===0,'unattended level-one machine waits for operator');F.manual(m,1);advance(m,8500);check(F.total(m,'raw')===0,'manual output waits for visible processing completion');advance(m,100);check(F.total(m,'raw')===1,'manual batch arrives once');advance(m,30000);check(F.total(m,'raw')===1,'one manual command does not secretly automate station');F.assign(m,1);advance(m,15000);check(F.total(m,'raw')>2,'assigning a worker creates autonomous production');
const a=F.fresh();a.started=true;a.buildings[1]={type:'supply',level:2,pending:0,worker:false,manual:false};advance(a,15000);check(F.total(a,'raw')>=4,'level-two automation works without an assigned worker');check(F.duration({level:3,worker:true},'work')<F.duration({level:1,worker:false},'work'),'upgrades and workers accelerate manufacturing');check(F.duration({level:3,worker:true},'fetch')<F.duration({level:1,worker:false},'fetch'),'procurement and input transport become faster');check(F.duration({level:3,worker:true},'delivery')<F.duration({level:1,worker:false},'delivery'),'shipping and sales deliveries become faster');
const snap=JSON.parse(JSON.stringify(a));advance(a,12000);advance(snap,12000);check(JSON.stringify(a)===JSON.stringify(snap),'mid-job save/reload gives exactly identical outputs');const stopped=JSON.stringify(a);a.started=false;F.step(a,4000);a.started=true;check(JSON.stringify(a)===stopped,'paused simulation preserves every remaining duration');
const relocation=F.fresh();relocation.started=true;relocation.buildings[1]={type:'supply',level:2,worker:true,pending:0,manual:false};advance(relocation,500);check(F.relocate(relocation,1,6)&&!relocation.buildings[1]&&relocation.buildings[6].level===2,'free relocation preserves upgrades and workers');check(relocation.jobs.length===0,'relocation cancels old spatial job safely');
const pickup=F.fresh();pickup.started=true;pickup.buildings[1]={type:'press',level:1,worker:true,pending:0,manual:false};pickup.stock.raw[0]=3;advance(pickup,1200);check(pickup.stock.raw[0]===3,'conveyor input remains in source until loading finishes');advance(pickup,100);check(pickup.stock.raw[0]===2,'input consumed at pickup');F.assign(pickup,1);check(pickup.stock.raw[0]===3&&!pickup.jobs.length,'reassignment returns reserved inputs once');
ctx.createMomentumFactoryComponent({});let reports=[],saves=0;Object.assign(ctx,{updateWeightForKey:(...a)=>reports.push(a),generateFromList:()=>({question:'cat',result:'חתול',options:['כלב','חתול'],questionIndex:0}),getSetItems:()=>4});const g=Object.assign(component.data(),component.methods,{currentAppId:'fixture',currentApp:{},score:0,$nextTick:()=>{},reloadProgress:()=>true,saveScore:()=>saves++,shuffle:x=>x,save:()=>{},focus:()=>{},phase:'ready',question:{result:'חתול'},options:['כלב','חתול'],questionIndex:0});Object.defineProperty(g,'play',{get:()=>F.preparePlay(g.factory)});g.answer(0);g.answer(0);check(reports.length===1&&reports[0][2]===1&&g.phase==='retry','incorrect answer reported exactly once');const q=g.question,o=g.options;g.retry();check(g.question===q&&g.options===o,'explicit retry keeps question and choices');g.answer(1);g.answer(1);check(reports.length===2&&g.factory.points===1&&saves===2,'correct answer reported and rewarded exactly once');check(g.clock().feedback===700,'correct feedback automatically advances after readable delay');g.phase='ready';g.reloadProgress=()=>false;g.answer(1);check(g.phase==='completed'&&g.factory.points===2,'engine completion stops next question after reward');g.stopped=true;g.phase='ready';g.answer(1);check(reports.length===3,'destroyed game rejects stale answers');
console.log(checks+' Momentum Factory checks passed. Winning strategy: '+s.earned+' answers, '+Math.round(s.time/1000)+' simulation seconds, '+s.sold+' sales.');
