// Isolated advanced-game fixtures for layout, timing and interruption checks.
const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs');
fs.mkdirSync('artifacts/momentum-factory',{recursive:true});let checks=0;function check(v,label){assert.ok(v,label);checks++;console.log('PASS',label);}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:1365,height:900},hasTouch:true});await context.addInitScript(()=>{delete Navigator.prototype.serviceWorker;});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.goto('http://127.0.0.1:8873/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>typeof BaseGameComponent!=='undefined');
 await page.evaluate(()=>{const id='grp-g611-13',a=getItemById(apps,id);setLocalStorage(getActivityMode()+'_'+id+'_Weights',getDataList(a.listName).map(()=>15));setLocalStorage(id+'_CurrentLevelProgress',{progress:0,total:999});setLocalStorage(id+'_new_items',[]);const f=MOMENTUM_FACTORY.fresh();f.employees=5;f.earned=f.spent=238;f.order=2;f.started=true;f.money=30;for(const [i,type]of MOMENTUM_FACTORY.order.entries())f.buildings[i+1]={type,level:3,pending:0,worker:true,manual:false};f.stock={raw:[0,0,9],parts:[0,0,9],products:[0,0,9],boxes:[0,0,9]};setLocalStorage(id+'_MomentumFactory_v1',{version:1,factory:f,opening:false,elapsed:47});location.hash='/play/momentum_factory/'+id;});await page.locator('.mf-run').waitFor();await page.locator('.mf-run').click();await page.clock.runFor(2700);
 check(await page.locator('.mf-game').evaluate(e=>e.__vue__.factory.jobs.some(j=>j.phase==='work')),'working-machine phase is visible');const animation=await page.locator('[data-machine="1"]').getAttribute('style');await page.clock.runFor(200);check(await page.locator('[data-machine="1"]').getAttribute('style')!==animation,'machine atlas follows production clock');
 for(const size of [{width:1365,height:900},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await page.screenshot({path:'artifacts/momentum-factory/advanced-'+size.width+'x'+size.height+'.png'});check(await page.locator('.mf-game').evaluate(e=>e.scrollWidth===innerWidth&&e.scrollHeight===innerHeight),'advanced factory fills viewport without document overflow '+size.width);}
 await page.setViewportSize({width:1365,height:900});await page.locator('.mf-study').click();await page.locator('.mf-game').evaluate(e=>{const g=e.__vue__;g.answer(g.options.indexOf(g.question.result));});await page.clock.runFor(250);const remaining=await page.locator('.mf-game').evaluate(e=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));return e.__vue__.clock().feedback;});await page.clock.runFor(5000);check(await page.locator('.mf-game').evaluate(e=>e.__vue__.clock().feedback)===remaining,'background freezes remaining success feedback delay');await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});await page.clock.runFor(200);check(await page.locator('.mf-game').evaluate(e=>e.__vue__.phase)==='resolved','resuming does not skip readable feedback');await page.clock.runFor(350);check(await page.locator('.mf-game').evaluate(e=>e.__vue__.phase)==='ready','remaining feedback completes normally');await page.locator('.mf-return').click();
 await page.locator('[data-site="1"]').click();await page.locator('.mf-context button').filter({hasText:'העברת התחנה'}).click();await page.locator('[data-site="6"]').click();check(await page.locator('.mf-game').evaluate(e=>!e.__vue__.factory.buildings[1]&&e.__vue__.factory.buildings[6].type==='supply'&&e.__vue__.factory.jobs.every(j=>j.site!==1&&j.source!==1)),'relocating cancels old source/destination paths and keeps upgraded station');
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('.mf-game').__vue__.reduced);check(await page.locator('.mf-game').evaluate(e=>e.__vue__.reduced),'reduced motion responds to preference changes');await page.locator('.mf-run').click();const frozen=await page.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory));await page.clock.runFor(5000);check(await page.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory))===frozen,'manual pause freezes advanced line');await page.locator('.mf-run').click();await page.clock.runFor(200);const instance=await page.locator('.mf-game').evaluateHandle(e=>e.__vue__);await page.locator('.mf-exit').click();await page.clock.runFor(2000);check(await instance.evaluate(g=>g.stopped&&g.clock().raf===null),'route-away marks instance stopped');check(errors.length===0,'no interruption or layout runtime errors');console.log(checks+' advanced runtime checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
