const {chromium}=require('playwright'),assert=require('assert');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:1365,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{delete Navigator.prototype.serviceWorker;});await p.clock.install();await p.clock.pauseAt(new Date(Date.now()+1000));await p.goto('http://127.0.0.1:8873/');await p.waitForFunction(()=>window.MOMENTUM_FACTORY);
 await p.evaluate(()=>{const id='grp-ch51-7',a=getItemById(apps,id);setLocalStorage(getActivityMode()+'_'+id+'_Weights',getDataList(a.listName).map(()=>50));setLocalStorage(id+'_CurrentLevelProgress',{progress:0,total:9999});setLocalStorage(id+'_new_items',[]);location.hash='/play/momentum_factory/'+id;});
 await p.locator('.mf-start').waitFor();await p.screenshot({path:'artifacts/momentum-factory/robo-welcome.png'});await p.locator('.mf-start').click();await p.locator('.mf-guide-action').click();
 for(let i=0;i<3;i++){await p.locator('.mf-game').evaluate(e=>{const g=e.__vue__;g.answer(g.options.indexOf(g.question.result));g.answer(g.options.indexOf(g.question.result));});await p.clock.runFor(720);}
 assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.play.energy===3&&e.__vue__.factory.points===3));await p.locator('.mf-return').click();await p.locator('.mf-guide-action').click();
 assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.buildings[1]&&e.__vue__.factory.points===0));await p.locator('.mf-turbo').click();await p.clock.runFor(1600);
 assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.buildings[1].pending===0&&e.__vue__.factory.buildings[1].worker&&e.__vue__.play.boost>0));await p.clock.runFor(350);
 await p.locator('.mf-study').click();const frozen=await p.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory));await p.clock.runFor(2000);assert.equal(await p.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory)),frozen,'question freezes boost with the whole world');await p.screenshot({path:'artifacts/momentum-factory/robo-learning.png'});await p.locator('.mf-return').click();
 await p.locator('.mf-run').click();const remaining=await p.locator('.mf-game').evaluate(e=>e.__vue__.play.boost);await p.reload();await p.locator('.mf-turbo').waitFor();assert.equal(await p.locator('.mf-game').evaluate(e=>e.__vue__.play.boost),remaining);
 await p.locator('.mf-collection-open').click();assert.equal(await p.locator('.mf-badge-grid .is-locked').count(),7);await p.screenshot({path:'artifacts/momentum-factory/robo-collection.png'});await p.locator('.mf-context header button').click();await p.locator('.mf-sound').click();assert.equal(await p.locator('.mf-sound').getAttribute('aria-pressed'),'false');
 // Normal economy builds the full visual fixture; no runtime funding controls exist.
 await p.locator('.mf-game').evaluate(e=>{const g=e.__vue__,F=MOMENTUM_FACTORY;for(let i=0;i<240;i++)F.reward(g.factory);for(let i=1;i<5;i++)F.buy(g.factory,i+1,F.order[i]);for(let i=0;i<4;i++)F.hire(g.factory);g.factory.started=true;for(let t=0;t<3200;t+=100)F.step(g.factory,100);for(let i=2;i<=5;i++)F.assign(g.factory,i);g.phase='running';g.notice=null;});await p.clock.runFor(15000);
 for(const [w,h]of [[1365,900],[390,844],[844,390],[320,568]]){await p.setViewportSize({width:w,height:h});await p.screenshot({path:`artifacts/momentum-factory/robo-factory-${w}.png`});assert(await p.locator('.mf-guide-action').evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth&&r.y>=0&&r.bottom<=innerHeight;}));}
 await p.setViewportSize({width:1365,height:900});for(const key of await p.evaluate(()=>Object.keys(themeOptions))){await p.locator('.mf-game').evaluate((e,k)=>e.__vue__.theme=themeOptions[k],key);await p.screenshot({path:`artifacts/momentum-factory/robo-theme-${key}.png`});}
 await p.locator('.mf-game').evaluate(e=>e.__vue__.theme=themeOptions.base);let elapsed=0;while(!await p.locator('.mf-next-order').count()){await p.clock.runFor(3000);if((elapsed+=3000)>240000)throw Error('order did not finish');}
 await p.screenshot({path:'artifacts/momentum-factory/robo-milestone.png'});await p.locator('.mf-next-order').click();await p.locator('.mf-collection-open').click();await p.locator('.mf-badge-grid button').filter({hasText:'הצוות הירוק'}).click();assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.play.skin==='mint'));await p.locator('.mf-context header button').click();await p.reload();await p.locator('.mf-game.mf-skin-mint').waitFor();assert.equal(await p.locator('.mf-sound').getAttribute('aria-pressed'),'false');assert.deepEqual(errors,[]);
 console.log('PASS real three-answer starter, one reward/charge per answer, turbo installation, question freeze, mid-boost reload, collection locks, earned robot selection, mute persistence, all themes and four gameplay sizes');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
