const {chromium}=require('playwright'),fs=require('fs'),crypto=require('crypto'),assert=require('assert');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await browser.newPage({viewport:{width:1365,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install();await p.clock.pauseAt(new Date(Date.now()+1000));await p.goto('http://127.0.0.1:8873/');await p.waitForFunction(()=>window.MOMENTUM_FACTORY&&navigator.serviceWorker.controller);
 await p.evaluate(async()=>{const cache=await caches.open('my-app-cache-v213-paid-production-belts');for(const n of ['worker','worker-task'])await cache.put('/assets/momentum-factory/'+n+'.png',new Response('stale-robot',{headers:{'Content-Type':'image/png'}}));const id='grp-ch51-7',F=MOMENTUM_FACTORY,s=F.fresh();F.prepareMarket(s);F.preparePlay(s);s.started=true;s.employees=3;for(let i=0;i<3;i++)s.buildings[i+1]={type:F.order[i],level:1,worker:true,pending:0,manual:false};s.stock.products[0]=17;s.market.visits=1;setLocalStorage(id+'_MomentumFactory_v1',{version:1,factory:s,opening:false,elapsed:0});const a=getItemById(apps,id);setLocalStorage(getActivityMode()+'_'+id+'_Weights',getDataList(a.listName).map(()=>50));setLocalStorage(id+'_new_items',[]);setLocalStorage(id+'_CurrentLevelProgress',{progress:0,total:9999});location.hash='/play/momentum_factory/'+id;});await p.locator('.mf-run').click();assert.equal(await p.locator('.mf-special-visitor').count(),0,'no manual request interrupts automatic shop');
 assert.equal(await p.locator('.mf-game').evaluate(e=>e.__vue__.connections.length),0,'no free conveyors');
 await p.clock.runFor(1400);const cargo=await p.locator('[data-job="1"]').getAttribute('style');assert.equal(await p.locator('[data-job="1"] .mf-gait').count(),1,'initial employee carries materials');await p.clock.runFor(200);assert.notEqual(await p.locator('[data-job="1"]').getAttribute('style'),cargo);assert.equal(await p.locator('[data-operator="1"]').count(),0,'no duplicate operator while walking');assert.equal(await p.locator('[data-porter] .mf-gait').count(),1,'human shop courier');
 const idleUrl=await p.locator('[data-job="1"] .mf-gait').evaluate(e=>getComputedStyle(e).backgroundImage.slice(5,-2));await p.clock.runFor(1400);const workUrl=await p.locator('[data-operator="1"] .mf-gait').evaluate(e=>getComputedStyle(e).backgroundImage.slice(5,-2));assert(workUrl.includes('worker-task.png?v='));assert(idleUrl.includes('worker.png?v='));
 for(const [name,url]of [['worker',idleUrl],['worker-task',workUrl]]){const hash=await p.evaluate(async url=>{const a=await(await fetch(url)).arrayBuffer();return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',a))).map(n=>n.toString(16).padStart(2,'0')).join('');},url);assert.equal(hash,crypto.createHash('sha256').update(fs.readFileSync('assets/momentum-factory/'+name+'.png')).digest('hex'),'fresh Knight atlas even with stale bare URL cached');}
 await p.clock.runFor(20000);assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.money>0&&e.__vue__.market.visits>2&&!e.__vue__.play.special&&e.__vue__.factory.stock.products[0]<17));
 await p.locator('.mf-speed-open').click();assert((await p.locator('.mf-speed-dialog').innerText()).includes('מסוע'));const cash=await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.money);await p.locator('.mf-speed-action').click();assert.equal(await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.money),cash-10);assert.equal(await p.locator('.mf-game').evaluate(e=>e.__vue__.connections.length),1);assert(await p.locator('.mf-game').evaluate(e=>e.__vue__.connections.every(l=>Number.isInteger(l.a)&&Number.isInteger(l.b))),'no belts to forest or shop');
 for(let i=0;i<100;i++){if(await p.locator('.mf-game').evaluate(e=>e.__vue__.factory.jobs.some(j=>j.site===2&&j.phase==='fetch')))break;await p.clock.runFor(100);}assert.equal(await p.locator('[data-job="2"] .mf-gait').count(),0,'paid conveyor carries materials');assert.equal(await p.locator('[data-operator="2"]').count(),1,'operator stays by conveyor-fed machine');
 for(const [w,h]of [[1365,900],[390,844],[844,390]]){await p.setViewportSize({width:w,height:h});await p.clock.runFor(200);await p.screenshot({path:'artifacts/momentum-factory/conveyors-'+w+'.png'});}await p.locator('.mf-study').click();const paused=await p.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory));await p.clock.runFor(2000);assert.equal(await p.locator('.mf-game').evaluate(e=>JSON.stringify(e.__vue__.factory)),paused);assert.deepEqual(errors,[]);console.log('PASS screenshot backlog sells unattended, paid internal conveyors replace carrying, human shop service, both Knight atlases bypass stale robot cache, three viewport screenshots and learning pause');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
